subdir-ccflags-y += -I$(src)

obj-y := core.o sysfs.o
obj-$(CONFIG_SPRD_MIPI_LOG_R4P2) += serdes.o
obj-$(CONFIG_SPRD_MIPI_LOG_R4P2) += r4p2/

obj-$(CONFIG_SPRD_MIPI_LOG_R0P0) += whale2/
obj-$(CONFIG_SPRD_MIPI_LOG_R1P0) += sharkl2/
obj-$(CONFIG_SPRD_MIPI_LOG_R2P0) += sharkle/
obj-$(CONFIG_SPRD_MIPI_LOG_R3P0) += isharkl2/
obj-$(CONFIG_SPRD_MIPI_LOG_R4P0) += sharklj1/
