
SDIOMFILES+= sdiom_debug.o
SDIOMFILES+= sdiom_depend.o
SDIOMFILES+= sdiom_rx_adapt.o
SDIOMFILES+= sdiom_rx_api.o
SDIOMFILES+= sdiom_rx_core.o
SDIOMFILES+= sdiom_rx_parser.o
SDIOMFILES+= sdiom_rx_recvbuf.o
SDIOMFILES+= sdiom_rx_default.o
SDIOMFILES+= sdiom_rx_trans.o
SDIOMFILES+= sdiom_tx_api.o
SDIOMFILES+= sdiom_tx_core.o
SDIOMFILES+= sdiom_tx_fifo.o
SDIOMFILES+= sdiom_tx_packer.o
SDIOMFILES+= sdiom_tx_sendbuf.o
SDIOMFILES+= sdiom_tx_trans.o
SDIOMFILES+= sdiom_sleep.o
SDIOMFILES+= sdiom_packer_main.o
SDIOMFILES+= sdiom.o


obj-$(CONFIG_SDIOM) += sdiom_packer.o
sdiom_packer-objs += $(SDIOMFILES)

