#
# Makefile for the sprd staging modem files
#

obj-$(CONFIG_SPRD_MAILBOX)	+= mailbox/
obj-$(CONFIG_SPRD_SIPC)		+= sipc/
obj-$(CONFIG_SPRD_CPROC)	+= cproc/
obj-$(CONFIG_SPRD_MODEM_CTRL)	+= modem_control/
obj-$(CONFIG_SPRD_IQ)		+= iq/
obj-$(CONFIG_SPRD_MODEM_DEBUG)	+= debug_log/
