obj-$(CONFIG_TOUCHSCREEN_MSTAR2XXX)	+= mstar_drv_sprd.o \
                                       mstar_drv_main.o \
                                       mstar_drv_platform_interface.o    \
                                       mstar_drv_platform_porting_layer.o \
                                       mstar_drv_self_fw_control.o  \
                                       mstar_drv_utility_adaption.o 

