#ifndef ALTEK_AHB
#define ALTEK_AHB

#ifdef _ISP_NONOS_ENV_
#include "sci_types.h"
#endif

#include "altek_ahb_reg.h"
#include "altek_os_info.h"

/* v1.0064 used by G2v1 branch and G2v3 starts with v1.1000 */
#define VERSION "v1.1107"


#define ALTEK_ISP_LOG_TAG "[altek]"

/* For isp log task */
/* #define DEBUG_ALTEK_LOG_TASK */

/*  While looping if wait for irq is timeout */
/* #define DEBUG_JTAG */

/*
 * /////////////////////////////////////////////////////////
 *                     Constant Definition                *
 * ////////////////////////////////////////////////////////
 */
/*  ahb register entry id number */
#define AHB_ENTRY_SYS_CONTROL					(0)
#define AHB_ENTRY_SYS_INFO					(1)
#define AHB_ENTRY_SYS_STATUS					(2)
#define AHB_ENTRY_SYS_MESSAGE					(3)
#define AHB_ENTRY_SYS_SENSOR_OUT_INDEX				(4)
#define AHB_ENTRY_SYS_CHANGE_OUT_SETTING_INFO			(5)
#define AHB_ENTRY_SYS_LOG_BUF_WRITE_PTR				(6)
#define AHB_ENTRY_SYS_LOG_BUF_SIZE				(7)
#define AHB_ENTRY_SYS_LOG_BUF_ADDR                              (8)
#define AHB_ENTRY_SYS_WORK_BUF_SIZE                             (9)
#define AHB_ENTRY_SYS_WORK_BUF_ADDR                             (10)
#define AHB_ENTRY_SYS_EXT_BUF_INFO                              (11)
#define AHB_ENTRY_SYS_GSENSOR_VECTOR_1                          (12)
#define AHB_ENTRY_SYS_GSENSOR_VECTOR_2                          (13)
#define AHB_ENTRY_SYS_CMD_TOKEN_ADDR                            (14)
#define AHB_ENTRY_COMMAND_SYSTEM                                (15)
#define AHB_ENTRY_COMMAND_SENSOR_1_GROUP1                       (16)
#define AHB_ENTRY_COMMAND_SENSOR_1_GROUP2                       (17)
#define AHB_ENTRY_COMMAND_SENSOR_2_GROUP1                       (18)
#define AHB_ENTRY_COMMAND_SENSOR_2_GROUP2                       (19)
#define AHB_ENTRY_COMMAND_SENSOR_3_GROUP1                       (20)
#define AHB_ENTRY_COMMAND_SENSOR_3_GROUP2                       (21)
#define AHB_ENTRY_INT_SYS_ENABLE                                (22)
#define AHB_ENTRY_INT_SYS_STATUS                                (23)
#define AHB_ENTRY_SENSOR_1_CONFIG_ADDR                          (24)
#define AHB_ENTRY_SENSOR_1_YUY2_USER_DEF_ADDR                   (25)
#define AHB_ENTRY_SENSOR_1_TONEMAP_DATA_ADDR                    (26)
#define AHB_ENTRY_SENSOR_1_MOTION_DATA_ADDR                     (27)
#define AHB_ENTRY_SENSOR_1_OUT_IMG_TYPE                         (28)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_RESOLUTION                  (29)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_RESOLUTION                  (30)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_RESOLUTION                  (31)
#define AHB_ENTRY_SENSOR_1_OUT_LINE_OFFSET_1                    (32)
#define AHB_ENTRY_SENSOR_1_OUT_LINE_OFFSET_2                    (33)
#define AHB_ENTRY_SENSOR_1_OUT_ENABLE                           (34)
#define AHB_ENTRY_SENSOR_1_OUT_BUF_NUM                          (35)
#define AHB_ENTRY_SENSOR_1_OUT_BUF_NUM_2                        (36)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR1                       (37)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR2                       (38)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR3                       (39)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR4                       (40)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR1                       (41)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR2                       (42)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR3                       (43)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR4                       (44)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR1                       (45)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR2                       (46)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR3                       (47)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR4                       (48)
#define AHB_ENTRY_SENSOR_1_OUT_STATICS_ADDR1                    (49)
#define AHB_ENTRY_SENSOR_1_OUT_STATICS_ADDR2                    (50)
#define AHB_ENTRY_SENSOR_1_OUT_STATICS_ADDR3                    (51)
#define AHB_ENTRY_SENSOR_1_OUT_STATICS_ADDR4                    (52)
#define AHB_ENTRY_SENSOR_1_OUT_AF_STATICS_ADDR1                 (53)
#define AHB_ENTRY_SENSOR_1_OUT_AF_STATICS_ADDR2                 (54)
#define AHB_ENTRY_SENSOR_1_OUT_AF_STATICS_ADDR3                 (55)
#define AHB_ENTRY_SENSOR_1_OUT_AF_STATICS_ADDR4                 (56)
#define AHB_ENTRY_SENSOR_1_OUT_RAW_ADD1                         (57)
#define AHB_ENTRY_SENSOR_1_OUT_RAW_ADD2                         (58)
#define AHB_ENTRY_SENSOR_1_OUT_RAW_ADD3                         (59)
#define AHB_ENTRY_SENSOR_1_OUT_RAW_ADD4                         (60)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR1_ISP1                  (61)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR2_ISP1                  (62)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR3_ISP1                  (63)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR4_ISP1                  (64)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR1_ISP1                  (65)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR2_ISP1                  (66)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR3_ISP1                  (67)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR4_ISP1                  (68)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR1_ISP1                  (69)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR2_ISP1                  (70)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR3_ISP1                  (71)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR4_ISP1                  (72)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR1_NV12_UV               (73)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR2_NV12_UV               (74)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR3_NV12_UV               (75)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR4_NV12_UV               (76)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR1_NV12_UV               (77)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR2_NV12_UV               (78)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR3_NV12_UV               (79)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR4_NV12_UV               (80)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR1_NV12_UV               (81)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR2_NV12_UV               (82)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR3_NV12_UV               (83)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR4_NV12_UV               (84)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR1_NV12_UV_ISP1          (85)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR2_NV12_UV_ISP1          (86)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR3_NV12_UV_ISP1          (87)
#define AHB_ENTRY_SENSOR_1_OUT_IMG1_ADDR4_NV12_UV_ISP1          (88)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR1_NV12_UV_ISP1          (89)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR2_NV12_UV_ISP1          (90)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR3_NV12_UV_ISP1          (91)
#define AHB_ENTRY_SENSOR_1_OUT_IMG2_ADDR4_NV12_UV_ISP1          (92)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR1_NV12_UV_ISP1          (93)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR2_NV12_UV_ISP1          (94)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR3_NV12_UV_ISP1          (95)
#define AHB_ENTRY_SENSOR_1_OUT_IMG3_ADDR4_NV12_UV_ISP1          (96)
#define AHB_ENTRY_SENSOR_1_QUALITY_SETTING1                     (97)
#define AHB_ENTRY_SENSOR_1_DLD3ASEQ_ADDR                        (98)
#define AHB_ENTRY_SENSOR_1_CFG3A_ADDR                           (99)
#define AHB_ENTRY_SENSOR_1_DZOOMINFO_ADDR                       (100)
#define AHB_ENTRY_SENSOR_1_QMERGE_ADDR                          (101)
#define AHB_ENTRY_SENSOR_1_SHADING_ADDR                         (102)
#define AHB_ENTRY_SENSOR_1_CBC_MAP_ADDR                         (103)
#define AHB_ENTRY_SENSOR_1_DETECT_SETTING1                      (104)
#define AHB_ENTRY_SENSOR_1_DETECT_SETTING2                      (105)
#define AHB_ENTRY_SENSOR_1_DETECT_SETTING3                      (106)
#define AHB_ENTRY_SENSOR_1_DETECT_SETTING4                      (107)
#define AHB_ENTRY_SENSOR_1_DETECT_SETTING5                      (108)
#define AHB_ENTRY_SENSOR_1_DEBUG_INFO_ADDR                      (109)
#define AHB_ENTRY_SENSOR_1_CCM_INFO_ADDR                        (110)
#define AHB_ENTRY_SENSOR_1_IQ_OTP_INFO_ADDR                     (111)
#define AHB_ENTRY_SENSOR_1_VALID_EXPOSURE_TIME                  (112)
#define AHB_ENTRY_SENSOR_1_VALID_AD_GAIN                        (113)
#define AHB_ENTRY_SENSOR_1_COLOR_TEMPERATURE                    (114)
#define AHB_ENTRY_SENSOR_1_BRIGHTNESS_SETTING_ADDR              (115)
#define AHB_ENTRY_SENSOR_1_RAW_SETTING                          (116)
#define AHB_ENTRY_SENSOR_1_RAW_INFO_ADDR                        (117)
#define AHB_ENTRY_SENSOR_1_PROC_STILL_ADDR                      (118)
#define AHB_ENTRY_SENSOR_1_AD_SHAD_BUF_ADDR                     (119)
#define AHB_ENTRY_SENSOR_1_IQ_INFO_ADDR                         (120)
#define AHB_ENTRY_SENSOR_1_ISP_D_GAIN_ADDR                      (121)
#define AHB_ENTRY_SENSOR_1_Y_OFFSET                             (122)
#define AHB_ENTRY_SENSOR_1_IQ_PARAM_INDEX_SETTING               (123)
#define AHB_ENTRY_SENSOR_2_YUY2_USER_DEF_ADDR                   (124)
#define AHB_ENTRY_SENSOR_2_TONEMAP_DATA_ADDR                    (125)
#define AHB_ENTRY_SENSOR_2_MOTION_DATA_ADDR                     (126)
#define AHB_ENTRY_SENSOR_2_OUT_IMG_TYPE                         (127)
#define AHB_ENTRY_SENSOR_2_OUT_IMG1_RESOLUTION                  (128)
#define AHB_ENTRY_SENSOR_2_OUT_IMG2_RESOLUTION                  (129)
#define AHB_ENTRY_SENSOR_2_OUT_IMG3_RESOLUTION                  (130)
#define AHB_ENTRY_SENSOR_2_OUT_LINE_OFFSET_1                    (131)
#define AHB_ENTRY_SENSOR_2_OUT_LINE_OFFSET_2                    (132)
#define AHB_ENTRY_SENSOR_2_OUT_ENABLE                           (133)
#define AHB_ENTRY_SENSOR_2_OUT_BUF_NUM                          (134)
#define AHB_ENTRY_SENSOR_2_OUT_IMG1_ADDR1                       (135)
#define AHB_ENTRY_SENSOR_2_OUT_IMG1_ADDR2                       (136)
#define AHB_ENTRY_SENSOR_2_OUT_IMG1_ADDR3                       (137)
#define AHB_ENTRY_SENSOR_2_OUT_IMG1_ADDR4                       (138)
#define AHB_ENTRY_SENSOR_2_OUT_IMG2_ADDR1                       (139)
#define AHB_ENTRY_SENSOR_2_OUT_IMG2_ADDR2                       (140)
#define AHB_ENTRY_SENSOR_2_OUT_IMG2_ADDR3                       (141)
#define AHB_ENTRY_SENSOR_2_OUT_IMG2_ADDR4                       (142)
#define AHB_ENTRY_SENSOR_2_OUT_IMG3_ADDR1                       (143)
#define AHB_ENTRY_SENSOR_2_OUT_IMG3_ADDR2                       (144)
#define AHB_ENTRY_SENSOR_2_OUT_IMG3_ADDR3                       (145)
#define AHB_ENTRY_SENSOR_2_OUT_IMG3_ADDR4                       (146)
#define AHB_ENTRY_SENSOR_2_OUT_STATICS_ADDR1                    (147)
#define AHB_ENTRY_SENSOR_2_OUT_STATICS_ADDR2                    (148)
#define AHB_ENTRY_SENSOR_2_OUT_STATICS_ADDR3                    (149)
#define AHB_ENTRY_SENSOR_2_OUT_STATICS_ADDR4                    (150)
#define AHB_ENTRY_SENSOR_2_OUT_AF_STATICS_ADDR1                 (151)
#define AHB_ENTRY_SENSOR_2_OUT_AF_STATICS_ADDR2                 (152)
#define AHB_ENTRY_SENSOR_2_OUT_AF_STATICS_ADDR3                 (153)
#define AHB_ENTRY_SENSOR_2_OUT_AF_STATICS_ADDR4                 (154)
#define AHB_ENTRY_SENSOR_2_OUT_IMG1_ADDR1_NV12_UV               (155)
#define AHB_ENTRY_SENSOR_2_OUT_IMG1_ADDR2_NV12_UV               (156)
#define AHB_ENTRY_SENSOR_2_OUT_IMG1_ADDR3_NV12_UV               (157)
#define AHB_ENTRY_SENSOR_2_OUT_IMG1_ADDR4_NV12_UV               (158)
#define AHB_ENTRY_SENSOR_2_OUT_IMG2_ADDR1_NV12_UV               (159)
#define AHB_ENTRY_SENSOR_2_OUT_IMG2_ADDR2_NV12_UV               (160)
#define AHB_ENTRY_SENSOR_2_OUT_IMG2_ADDR3_NV12_UV               (161)
#define AHB_ENTRY_SENSOR_2_OUT_IMG2_ADDR4_NV12_UV               (162)
#define AHB_ENTRY_SENSOR_2_OUT_IMG3_ADDR1_NV12_UV               (163)
#define AHB_ENTRY_SENSOR_2_OUT_IMG3_ADDR2_NV12_UV               (164)
#define AHB_ENTRY_SENSOR_2_OUT_IMG3_ADDR3_NV12_UV               (165)
#define AHB_ENTRY_SENSOR_2_OUT_IMG3_ADDR4_NV12_UV               (166)
#define AHB_ENTRY_SENSOR_2_QUALITY_SETTING1                     (167)
#define AHB_ENTRY_SENSOR_2_DLD3ASEQ_ADDR                        (168)
#define AHB_ENTRY_SENSOR_2_CFG3A_ADDR                           (169)
#define AHB_ENTRY_SENSOR_2_DZOOMINFO_ADDR                       (170)
#define AHB_ENTRY_SENSOR_2_QMERGE_ADDR                          (171)
#define AHB_ENTRY_SENSOR_2_SHADING_ADDR                         (172)
#define AHB_ENTRY_SENSOR_2_CBC_MAP_ADDR                         (173)
#define AHB_ENTRY_SENSOR_2_DETECT_SETTING1                      (174)
#define AHB_ENTRY_SENSOR_2_DETECT_SETTING2                      (175)
#define AHB_ENTRY_SENSOR_2_DETECT_SETTING3                      (176)
#define AHB_ENTRY_SENSOR_2_DETECT_SETTING4                      (177)
#define AHB_ENTRY_SENSOR_2_DETECT_SETTING5                      (178)
#define AHB_ENTRY_SENSOR_2_DEBUG_INFO_ADDR                      (179)
#define AHB_ENTRY_SENSOR_2_CCM_INFO_ADDR                        (180)
#define AHB_ENTRY_SENSOR_2_IQ_OTP_INFO_ADDR                     (181)
#define AHB_ENTRY_SENSOR_2_VALID_EXPOSURE_TIME                  (182)
#define AHB_ENTRY_SENSOR_2_VALID_AD_GAIN                        (183)
#define AHB_ENTRY_SENSOR_2_COLOR_TEMPERATURE                    (184)
#define AHB_ENTRY_SENSOR_2_BRIGHTNESS_SETTING_ADDR              (185)
#define AHB_ENTRY_SENSOR_2_RAW_SETTING                          (186)
#define AHB_ENTRY_SENSOR_2_AD_SHAD_BUF_ADDR                     (187)
#define AHB_ENTRY_SENSOR_2_IQ_INFO_ADDR                         (188)
#define AHB_ENTRY_SENSOR_2_ISP_D_GAIN_ADDR                      (189)
#define AHB_ENTRY_SENSOR_2_Y_OFFSET                             (190)
#define AHB_ENTRY_SENSOR_2_IQ_PARAM_INDEX_SETTING               (191)
#define AHB_ENTRY_SENSOR_3_YUY2_USER_DEF_ADDR                   (192)
#define AHB_ENTRY_SENSOR_3_TONEMAP_DATA_ADDR                    (193)
#define AHB_ENTRY_SENSOR_3_MOTION_DATA_ADDR                     (194)
#define AHB_ENTRY_SENSOR_3_OUT_IMG_TYPE                         (195)
#define AHB_ENTRY_SENSOR_3_OUT_IMG1_RESOLUTION                  (196)
#define AHB_ENTRY_SENSOR_3_OUT_LINE_OFFSET                      (197)
#define AHB_ENTRY_SENSOR_3_OUT_ENABLE                           (198)
#define AHB_ENTRY_SENSOR_3_OUT_BUF_NUM                          (199)
#define AHB_ENTRY_SENSOR_3_OUT_IMG1_ADDR1                       (200)
#define AHB_ENTRY_SENSOR_3_OUT_IMG1_ADDR2                       (201)
#define AHB_ENTRY_SENSOR_3_OUT_IMG1_ADDR3                       (202)
#define AHB_ENTRY_SENSOR_3_OUT_IMG1_ADDR4                       (203)
#define AHB_ENTRY_SENSOR_3_OUT_STATICS_ADDR1                    (204)
#define AHB_ENTRY_SENSOR_3_OUT_STATICS_ADDR2                    (205)
#define AHB_ENTRY_SENSOR_3_OUT_STATICS_ADDR3                    (206)
#define AHB_ENTRY_SENSOR_3_OUT_STATICS_ADDR4                    (207)
#define AHB_ENTRY_SENSOR_3_OUT_AF_STATICS_ADDR1                 (208)
#define AHB_ENTRY_SENSOR_3_OUT_AF_STATICS_ADDR2                 (209)
#define AHB_ENTRY_SENSOR_3_OUT_AF_STATICS_ADDR3                 (210)
#define AHB_ENTRY_SENSOR_3_OUT_AF_STATICS_ADDR4                 (211)
#define AHB_ENTRY_SENSOR_3_OUT_IMG1_ADDR1_NV12_UV               (212)
#define AHB_ENTRY_SENSOR_3_OUT_IMG1_ADDR2_NV12_UV               (213)
#define AHB_ENTRY_SENSOR_3_OUT_IMG1_ADDR3_NV12_UV               (214)
#define AHB_ENTRY_SENSOR_3_OUT_IMG1_ADDR4_NV12_UV               (215)
#define AHB_ENTRY_SENSOR_3_QUALITY_SETTING1                     (216)
#define AHB_ENTRY_SENSOR_3_DLD3ASEQ_ADDR                        (217)
#define AHB_ENTRY_SENSOR_3_CFG3A_ADDR                           (218)
#define AHB_ENTRY_SENSOR_3_DZOOMINFO_ADDR                       (219)
#define AHB_ENTRY_SENSOR_3_QMERGE_ADDR                          (220)
#define AHB_ENTRY_SENSOR_3_SHADING_ADDR                         (221)
#define AHB_ENTRY_SENSOR_3_CBC_MAP_ADDR                         (222)
#define AHB_ENTRY_SENSOR_3_DETECT_SETTING1                      (223)
#define AHB_ENTRY_SENSOR_3_DETECT_SETTING2                      (224)
#define AHB_ENTRY_SENSOR_3_DETECT_SETTING3                      (225)
#define AHB_ENTRY_SENSOR_3_DETECT_SETTING4                      (226)
#define AHB_ENTRY_SENSOR_3_DETECT_SETTING5                      (227)
#define AHB_ENTRY_SENSOR_3_DEBUG_INFO_ADDR                      (228)
#define AHB_ENTRY_SENSOR_3_CCM_INFO_ADDR                        (229)
#define AHB_ENTRY_SENSOR_3_IQ_OTP_INFO_ADDR                     (230)
#define AHB_ENTRY_SENSOR_3_VALID_EXPOSURE_TIME                  (231)
#define AHB_ENTRY_SENSOR_3_VALID_AD_GAIN                        (232)
#define AHB_ENTRY_SENSOR_3_COLOR_TEMPERATURE                    (233)
#define AHB_ENTRY_SENSOR_3_BRIGHTNESS_SETTING_ADDR              (234)
#define AHB_ENTRY_SENSOR_3_RAW_SETTING                          (235)
#define AHB_ENTRY_SENSOR_3_AD_SHAD_BUF_ADDR                     (236)
#define AHB_ENTRY_SENSOR_3_IQ_INFO_ADDR                         (237)
#define AHB_ENTRY_SENSOR_3_ISP_D_GAIN_ADDR                      (238)
#define AHB_ENTRY_SENSOR_3_Y_OFFSET                             (239)
#define AHB_ENTRY_SENSOR_3_IQ_PARAM_INDEX_SETTING               (240)
#define AHB_ENTRY_OVERLAP_PIXEL_NUM                             (241)
#define AHB_ENTRY_ISP_CHIP_ID                                   (242)
#define AHB_ENTRY_INT_SENSOR_1_ENABLE                           (243)
#define AHB_ENTRY_INT_SENSOR_2_ENABLE                           (244)
#define AHB_ENTRY_INT_SENSOR_3_ENABLE                           (245)
#define AHB_ENTRY_INT_SENSOR_1_IMG1_STATUS                      (246)
#define AHB_ENTRY_INT_SENSOR_1_IMG2_STATUS                      (247)
#define AHB_ENTRY_INT_SENSOR_1_IMG3_STATUS                      (248)
#define AHB_ENTRY_INT_SENSOR_1_3A_STATUS                        (249)
#define AHB_ENTRY_INT_SENSOR_1_AF_STATUS                        (250)
#define AHB_ENTRY_INT_SENSOR_1_ISP_SOF_STATUS                   (251)
#define AHB_ENTRY_INT_SENSOR_1_3A_LINEMEET_STATUS               (252)
#define AHB_ENTRY_INT_SENSOR_1_STILL_PROC_STATUS                (253)
#define AHB_ENTRY_INT_SENSOR_1_RAW_STATUS                       (254)
#define AHB_ENTRY_INT_SENSOR_2_IMG1_STATUS                      (255)
#define AHB_ENTRY_INT_SENSOR_2_IMG2_STATUS                      (256)
#define AHB_ENTRY_INT_SENSOR_2_IMG3_STATUS                      (257)
#define AHB_ENTRY_INT_SENSOR_2_3A_STATUS                        (258)
#define AHB_ENTRY_INT_SENSOR_2_AF_STATUS                        (259)
#define AHB_ENTRY_INT_SENSOR_2_ISP_SOF_STATUS                   (260)
#define AHB_ENTRY_INT_SENSOR_2_3A_LINEMEET_STATUS               (261)
#define AHB_ENTRY_INT_SENSOR_3_IMG_STATUS                       (262)
#define AHB_ENTRY_INT_SENSOR_3_3A_STATUS                        (263)
#define AHB_ENTRY_INT_SENSOR_3_AF_STATUS                        (264)
#define AHB_ENTRY_INT_SENSOR_3_ISP_SOF_STATUS                   (265)
#define AHB_ENTRY_INT_SENSOR_3_3A_LINEMEET_STATUS               (266)
#define AHB_ENTRY_TOTAL                                         (267)



/* ahb group entry range */
#define AHB_GROUP_00_RANGE_L                  (AHB_ENTRY_SYS_CONTROL)
#define AHB_GROUP_00_RANGE_H                  (AHB_ENTRY_SYS_CONTROL)
#define AHB_GROUP_01_RANGE_L                  (AHB_GROUP_00_RANGE_H+1)
#define AHB_GROUP_01_RANGE_H                  (AHB_GROUP_01_RANGE_L)
#define AHB_GROUP_02_RANGE_L                  (AHB_GROUP_01_RANGE_H+1)
#define AHB_GROUP_02_RANGE_H                  (AHB_GROUP_02_RANGE_L)
#define AHB_GROUP_03_RANGE_L                  (AHB_GROUP_02_RANGE_H+1)
#define AHB_GROUP_03_RANGE_H                  (AHB_GROUP_03_RANGE_L)
#define AHB_GROUP_04_RANGE_L                  (AHB_GROUP_03_RANGE_H+1)
#define AHB_GROUP_04_RANGE_H                  (AHB_GROUP_04_RANGE_L)
#define AHB_GROUP_05_RANGE_L                  (AHB_GROUP_04_RANGE_H+1)
#define AHB_GROUP_05_RANGE_H                  (AHB_GROUP_05_RANGE_L)
#define AHB_GROUP_06_RANGE_L                  (AHB_GROUP_05_RANGE_H+1)
#define AHB_GROUP_06_RANGE_H                  (AHB_GROUP_06_RANGE_L)
#define AHB_GROUP_07_RANGE_L                  (AHB_GROUP_06_RANGE_H+1)
#define AHB_GROUP_07_RANGE_H                  (AHB_GROUP_07_RANGE_L)
#define AHB_GROUP_08_RANGE_L                  (AHB_GROUP_07_RANGE_H+1)
#define AHB_GROUP_08_RANGE_H                  (AHB_GROUP_08_RANGE_L)
#define AHB_GROUP_09_RANGE_L                  (AHB_GROUP_08_RANGE_H+1)
#define AHB_GROUP_09_RANGE_H                  (AHB_GROUP_09_RANGE_L)
#define AHB_GROUP_10_RANGE_L                  (AHB_GROUP_09_RANGE_H+1)
#define AHB_GROUP_10_RANGE_H                  (AHB_GROUP_10_RANGE_L)
#define AHB_GROUP_11_RANGE_L                  (AHB_GROUP_10_RANGE_H+1)
#define AHB_GROUP_11_RANGE_H                  (AHB_GROUP_11_RANGE_L)
#define AHB_GROUP_12_RANGE_L                  (AHB_GROUP_11_RANGE_H+1)
#define AHB_GROUP_12_RANGE_H                  (AHB_GROUP_12_RANGE_L)
#define AHB_GROUP_13_RANGE_L                  (AHB_GROUP_12_RANGE_H+1)
#define AHB_GROUP_13_RANGE_H                  (AHB_GROUP_13_RANGE_L)
#define AHB_GROUP_14_RANGE_L                  (AHB_GROUP_13_RANGE_H+1)
#define AHB_GROUP_14_RANGE_H                  (AHB_GROUP_14_RANGE_L)
#define AHB_GROUP_15_RANGE_L                  (AHB_GROUP_14_RANGE_H+1)
#define AHB_GROUP_15_RANGE_H                  (AHB_GROUP_15_RANGE_L)
#define AHB_GROUP_16_RANGE_L                  (AHB_GROUP_15_RANGE_H+1)
#define AHB_GROUP_16_RANGE_H                  (AHB_GROUP_16_RANGE_L)
#define AHB_GROUP_17_RANGE_L                  (AHB_GROUP_16_RANGE_H+1)
#define AHB_GROUP_17_RANGE_H                  (AHB_GROUP_17_RANGE_L)
#define AHB_GROUP_18_RANGE_L                  (AHB_GROUP_17_RANGE_H+1)
#define AHB_GROUP_18_RANGE_H                  (AHB_GROUP_18_RANGE_L)
#define AHB_GROUP_19_RANGE_L                  (AHB_GROUP_18_RANGE_H+1)
#define AHB_GROUP_19_RANGE_H                  (AHB_GROUP_19_RANGE_L)
#define AHB_GROUP_20_RANGE_L                  (AHB_GROUP_19_RANGE_H+1)
#define AHB_GROUP_20_RANGE_H                  (AHB_GROUP_20_RANGE_L)
#define AHB_GROUP_21_RANGE_L                  (AHB_GROUP_20_RANGE_H+1)
#define AHB_GROUP_21_RANGE_H                  (AHB_GROUP_21_RANGE_L)
#define AHB_GROUP_22_RANGE_L                  (AHB_GROUP_21_RANGE_H+1)
#define AHB_GROUP_22_RANGE_H                  (AHB_GROUP_22_RANGE_L)
#define AHB_GROUP_23_RANGE_L                  (AHB_GROUP_22_RANGE_H+1)
#define AHB_GROUP_23_RANGE_H                  (AHB_GROUP_23_RANGE_L)
#define AHB_GROUP_24_RANGE_L                  (AHB_GROUP_23_RANGE_H+1)
#define AHB_GROUP_24_RANGE_H                  (AHB_GROUP_24_RANGE_L)
#define AHB_GROUP_25_RANGE_L                  (AHB_GROUP_24_RANGE_H+1)
#define AHB_GROUP_25_RANGE_H                  (AHB_GROUP_25_RANGE_L)
#define AHB_GROUP_26_RANGE_L                  (AHB_GROUP_25_RANGE_H+1)
#define AHB_GROUP_26_RANGE_H                  (AHB_GROUP_26_RANGE_L)
#define AHB_GROUP_27_RANGE_L                  (AHB_GROUP_26_RANGE_H+1)
#define AHB_GROUP_27_RANGE_H                  (AHB_GROUP_27_RANGE_L)
#define AHB_GROUP_28_RANGE_L                  (AHB_GROUP_27_RANGE_H+1)
#define AHB_GROUP_28_RANGE_H                  (AHB_GROUP_28_RANGE_L)
#define AHB_GROUP_29_RANGE_L                  (AHB_GROUP_28_RANGE_H+1)
#define AHB_GROUP_29_RANGE_H                  (AHB_GROUP_29_RANGE_L)
#define AHB_GROUP_30_RANGE_L                  (AHB_GROUP_29_RANGE_H+1)
#define AHB_GROUP_30_RANGE_H                  (AHB_GROUP_30_RANGE_L)
#define AHB_GROUP_31_RANGE_L                  (AHB_GROUP_30_RANGE_H+1)
#define AHB_GROUP_31_RANGE_H                  (AHB_GROUP_31_RANGE_L)



/* ahb field id */
#define AHB_ITEM_OPSTART                                        (0)
#define AHB_ITEM_HW_VERSION                                     (1)
#define AHB_ITEM_SW_VERSION                                     (2)
#define AHB_ITEM_IP_BUSY                                        (3)
#define AHB_ITEM_SENSOR1_BUSY                                   (4)
#define AHB_ITEM_SENSOR2_BUSY                                   (5)
#define AHB_ITEM_SENSOR3_BUSY                                   (6)
#define AHB_ITEM_SYSTEM_MESSAGE                                 (7)
#define AHB_ITEM_SENSOR1_OUT_IMG1_INDEX                         (8)
#define AHB_ITEM_SENSOR1_OUT_IMG2_INDEX                         (9)
#define AHB_ITEM_SENSOR1_OUT_IMG3_INDEX                         (10)
#define AHB_ITEM_SENSOR1_OUT_STATISTICS_INDEX                   (11)
#define AHB_ITEM_SENSOR1_OUT_AF_STATISTICS_INDEX                (12)
#define AHB_ITEM_SENSOR1_OUT_RAW_INDEX                          (13)
#define AHB_ITEM_SENSOR2_OUT_IMG1_INDEX                         (14)
#define AHB_ITEM_SENSOR2_OUT_IMG2_INDEX                         (15)
#define AHB_ITEM_SENSOR2_OUT_IMG3_INDEX                         (16)
#define AHB_ITEM_SENSOR2_OUT_STATISTICS_INDEX                   (17)
#define AHB_ITEM_SENSOR2_OUT_AF_STATISTICS_INDEX                (18)
#define AHB_ITEM_SENSOR3_OUT_IMG1_INDEX                         (19)
#define AHB_ITEM_SENSOR3_OUT_STATISTICS_INDEX                   (20)
#define AHB_ITEM_SENSOR3_OUT_AF_STATISTICS_INDEX                (21)
#define AHB_ITEM_CHANGE_SENSOR1_OUT_RESOLUTION_IMG              (22)
#define AHB_ITEM_CHAGNE_SENSOR1_OUT_ON_OFF_SETTING_IMG          (23)
#define AHB_ITEM_CHANGE_SENSOR1_OUT_ADDR_IMG                    (24)
#define AHB_ITEM_CHANGE_SENSOR1_OUT_ADDR_IDX                    (25)
#define AHB_ITEM_CHANGE_SENSOR2_OUT_RESOLUTION_IMG              (26)
#define AHB_ITEM_CHAGNE_SENSOR2_OUT_ON_OFF_SETTING_IMG          (27)
#define AHB_ITEM_CHANGE_SENSOR2_OUT_ADDR_IMG                    (28)
#define AHB_ITEM_CHANGE_SENSOR2_OUT_ADDR_IDX                    (29)
#define AHB_ITEM_CHAGNE_SENSOR3_OUT_ON_OFF_SETTING_IMG          (30)
#define AHB_ITEM_CHANGE_SENSOR3_OUT_ADDR_IMG                    (31)
#define AHB_ITEM_CHANGE_SENSOR3_OUT_ADDR_IDX                    (32)
#define AHB_ITEM_LOG_BUF_WRITE_POINTER                          (33)
#define AHB_ITEM_LOG_BUF_SIZE                                   (34)
#define AHB_ITEM_LOG_BUF_ADDR                                   (35)
#define AHB_ITEM_WORK_BUF_SIZE                                  (36)
#define AHB_ITEM_WORK_BUF_ADDR                                  (37)
#define AHB_ITEM_WORK_EXT_INFO                                  (38)
#define AHB_ITEM_GSENSOR_VECTOR_X                               (39)
#define AHB_ITEM_GSENSOR_VECTOR_Y                               (40)
#define AHB_ITEM_GSENSOR_VECTOR_Z                               (41)
#define AHB_ITEM_CMD_TOKEN_ADDR                                 (42)
#define AHB_ITEM_GET_SYS_INFO                                   (43)
#define AHB_ITEM_CHANGE_SENSOR1_SETTINGS                        (44)
#define AHB_ITEM_CHANGE_SENSOR2_SETTINGS                        (45)
#define AHB_ITEM_CHANGE_SENSOR3_SETTINGS                        (46)
#define AHB_ITEM_START_SENSOR1_ZSL_PATH                         (47)
#define AHB_ITEM_STOP_SENSOR1_PATH                              (48)
#define AHB_ITEM_DO_SENSOR1_PROC_STILL                          (49)
#define AHB_ITEM_START_SENSOR2_ZSL_PATH                         (50)
#define AHB_ITEM_STOP_SENSOR2_PATH                              (51)
#define AHB_ITEM_START_SENSOR3_ZSL_PATH                         (52)
#define AHB_ITEM_STOP_SENSOR3_PATH                              (53)
#define AHB_ITEM_CHANGE_GSENSOR_VECTOR                          (54)
#define AHB_ITEM_TEST_MODE_START                                (55)
#define AHB_ITEM_ENABLE_INDEPENDENT_AF_STATISTIC_DONE_INT       (56)
#define AHB_ITEM_CHANGE_SENSOR1_OUT_RESOLUTION                  (57)
#define AHB_ITEM_CHANGE_SENSOR1_OUT_ON_OFF_SETTING              (58)
#define AHB_ITEM_CHANGE_SENSOR1_OUT_ADDR                        (59)
#define AHB_ITEM_CHANGE_SENSOR1_CONTRAST                        (60)
#define AHB_ITEM_CHANGE_SENSOR1_SHARPNESS                       (61)
#define AHB_ITEM_CHANGE_SENSOR1_SATURATION                      (62)
#define AHB_ITEM_CHANGE_SENSOR1_SPECIAL_EFFECT                  (63)
#define AHB_ITEM_CHANGE_SENSOR1_TONEMAP_MODE                    (64)
#define AHB_ITEM_CHANGE_SENSOR1_YUY2_FORMAT                     (65)
#define AHB_ITEM_CHANGE_SENSOR1_SHADING                         (66)
#define AHB_ITEM_CHANGE_SENSOR1_FAST_CONVERGE_SETTING           (67)
#define AHB_ITEM_CHANGE_SENSOR1_BASICDLDSEQ_PREVIEW             (68)
#define AHB_ITEM_CHANGE_SENSOR1_ADVDLDSEQ_PREVIEW               (69)
#define AHB_ITEM_CHANGE_SENSOR1_BASICDLDSEQ_FASTCONVERGE        (70)
#define AHB_ITEM_CHANGE_SENSOR1_DETECTED_ISO                    (71)
#define AHB_ITEM_CHANGE_SENSOR1_DETECTED_AWB                    (72)
#define AHB_ITEM_CHANGE_SENSOR1_CONFIG_AE                       (73)
#define AHB_ITEM_CHANGE_SENSOR1_CONFIG_AWB                      (74)
#define AHB_ITEM_CHANGE_SENSOR1_CONFIG_AF                       (75)
#define AHB_ITEM_CHANGE_SENSOR1_CONFIG_YHIS                     (76)
#define AHB_ITEM_CHANGE_SENSOR1_CONFIG_ANTIFLICKER              (77)
#define AHB_ITEM_CHANGE_SENSOR1_CONFIG_SUBSAMPLE                (78)
#define AHB_ITEM_CHANGE_SENSOR1_SCENARIOINFO                    (79)
#define AHB_ITEM_CHANGE_SENSOR1_CROPSIZE                        (80)
#define AHB_ITEM_CHANGE_SENSOR1_BALANCED_AWB                    (81)
#define AHB_ITEM_CHANGE_SENSOR1_BRIGHTNESS                      (82)
#define AHB_ITEM_CHANGE_SENSOR1_CCM                             (83)
#define AHB_ITEM_CHANGE_SENSOR1_IQ_OTP_INFO                     (84)
#define AHB_ITEM_CHANGE_SENSOR1_VALID_EXPOSURE_TIME             (85)
#define AHB_ITEM_CHANGE_SENSOR1_VALID_AD_GAIN                   (86)
#define AHB_ITEM_CHANGE_SENSOR1_COLOR_TEMPERATURE               (87)
#define AHB_ITEM_CHANGE_SENSOR1_RAW_FRAME_RATE                  (88)
#define AHB_ITEM_CHANGE_SENSOR1_SCENE                           (89)
#define AHB_ITEM_CHANGE_SENSOR1_FLASH                           (90)
#define AHB_ITEM_CHANGE_SENSOR1_RAW_FORMAT                      (91)
#define AHB_ITEM_CHANGE_SENSOR1_ADAPTIVE_SHAD_BUF_INFO          (92)
#define AHB_ITEM_CHANGE_SENSOR1_IQ_INFO                         (93)
#define AHB_ITEM_CHANGE_SENSOR1_ISP_D_GAIN                      (94)
#define AHB_ITEM_CHANGE_SENSOR1_Y_OFFSET                        (95)
#define AHB_ITEM_CHANGE_SENSOR1_IQ_PARAM_IDX                    (96)
#define AHB_ITEM_CHANGE_SENSOR2_OUT_RESOLUTION                  (97)
#define AHB_ITEM_CHANGE_SENSOR2_OUT_ON_OFF_SETTING              (98)
#define AHB_ITEM_CHANGE_SENSOR2_OUT_ADDR                        (99)
#define AHB_ITEM_CHANGE_SENSOR2_CONTRAST                        (100)
#define AHB_ITEM_CHANGE_SENSOR2_SHARPNESS                       (101)
#define AHB_ITEM_CHANGE_SENSOR2_SATURATION                      (102)
#define AHB_ITEM_CHANGE_SENSOR2_SPECIAL_EFFECT                  (103)
#define AHB_ITEM_CHANGE_SENSOR2_TONEMAP_MODE                    (104)
#define AHB_ITEM_CHANGE_SENSOR2_YUY2_FORMAT                     (105)
#define AHB_ITEM_CHANGE_SENSOR2_SHADING                         (106)
#define AHB_ITEM_CHANGE_SENSOR2_FAST_CONVERGE_SETTING           (107)
#define AHB_ITEM_CHANGE_SENSOR2_BASICDLDSEQ_PREVIEW             (108)
#define AHB_ITEM_CHANGE_SENSOR2_ADVDLDSEQ_PREVIEW               (109)
#define AHB_ITEM_CHANGE_SENSOR2_BASICDLDSEQ_FASTCONVERGE        (110)
#define AHB_ITEM_CHANGE_SENSOR2_DETECTED_ISO                    (111)
#define AHB_ITEM_CHANGE_SENSOR2_DETECTED_AWB                    (112)
#define AHB_ITEM_CHANGE_SENSOR2_CONFIG_AE                       (113)
#define AHB_ITEM_CHANGE_SENSOR2_CONFIG_AWB                      (114)
#define AHB_ITEM_CHANGE_SENSOR2_CONFIG_AF                       (115)
#define AHB_ITEM_CHANGE_SENSOR2_CONFIG_YHIS                     (116)
#define AHB_ITEM_CHANGE_SENSOR2_CONFIG_ANTIFLICKER              (117)
#define AHB_ITEM_CHANGE_SENSOR2_CONFIG_SUBSAMPLE                (118)
#define AHB_ITEM_CHANGE_SENSOR2_SCENARIOINFO                    (119)
#define AHB_ITEM_CHANGE_SENSOR2_CROPSIZE                        (120)
#define AHB_ITEM_CHANGE_SENSOR2_BALANCED_AWB                    (121)
#define AHB_ITEM_CHANGE_SENSOR2_BRIGHTNESS                      (122)
#define AHB_ITEM_CHANGE_SENSOR2_CCM                             (123)
#define AHB_ITEM_CHANGE_SENSOR2_IQ_OTP_INFO                     (124)
#define AHB_ITEM_CHANGE_SENSOR2_VALID_EXPOSURE_TIME             (125)
#define AHB_ITEM_CHANGE_SENSOR2_VALID_AD_GAIN                   (126)
#define AHB_ITEM_CHANGE_SENSOR2_COLOR_TEMPERATURE               (127)
#define AHB_ITEM_CHANGE_SENSOR2_RAW_FRAME_RATE                  (128)
#define AHB_ITEM_CHANGE_SENSOR2_SCENE                           (129)
#define AHB_ITEM_CHANGE_SENSOR2_FLASH                           (130)
#define AHB_ITEM_CHANGE_SENSOR2_RAW_FORMAT                      (131)
#define AHB_ITEM_CHANGE_SENSOR2_ADAPTIVE_SHAD_BUF_INFO          (132)
#define AHB_ITEM_CHANGE_SENSOR2_IQ_INFO                         (133)
#define AHB_ITEM_CHANGE_SENSOR2_ISP_D_GAIN                      (134)
#define AHB_ITEM_CHANGE_SENSOR2_Y_OFFSET                        (135)
#define AHB_ITEM_CHANGE_SENSOR2_IQ_PARAM_IDX                    (136)
#define AHB_ITEM_CHANGE_SENSOR3_OUT_RESOLUTION                  (137)
#define AHB_ITEM_CHANGE_SENSOR3_OUT_ON_OFF_SETTING              (138)
#define AHB_ITEM_CHANGE_SENSOR3_OUT_ADDR                        (139)
#define AHB_ITEM_CHANGE_SENSOR3_CONTRAST                        (140)
#define AHB_ITEM_CHANGE_SENSOR3_SHARPNESS                       (141)
#define AHB_ITEM_CHANGE_SENSOR3_SATURATION                      (142)
#define AHB_ITEM_CHANGE_SENSOR3_SPECIAL_EFFECT                  (143)
#define AHB_ITEM_CHANGE_SENSOR3_TONEMAP_MODE                    (144)
#define AHB_ITEM_CHANGE_SENSOR3_YUY2_FORMAT                     (145)
#define AHB_ITEM_CHANGE_SENSOR3_SHADING                         (146)
#define AHB_ITEM_CHANGE_SENSOR3_FAST_CONVERGE_SETTING           (147)
#define AHB_ITEM_CHANGE_SENSOR3_BASICDLDSEQ_PREVIEW             (148)
#define AHB_ITEM_CHANGE_SENSOR3_ADVDLDSEQ_PREVIEW               (149)
#define AHB_ITEM_CHANGE_SENSOR3_BASICDLDSEQ_FASTCONVERGE        (150)
#define AHB_ITEM_CHANGE_SENSOR3_DETECTED_ISO                    (151)
#define AHB_ITEM_CHANGE_SENSOR3_DETECTED_AWB                    (152)
#define AHB_ITEM_CHANGE_SENSOR3_CONFIG_AE                       (153)
#define AHB_ITEM_CHANGE_SENSOR3_CONFIG_AWB                      (154)
#define AHB_ITEM_CHANGE_SENSOR3_CONFIG_AF                       (155)
#define AHB_ITEM_CHANGE_SENSOR3_CONFIG_YHIS                     (156)
#define AHB_ITEM_CHANGE_SENSOR3_CONFIG_ANTIFLICKER              (157)
#define AHB_ITEM_CHANGE_SENSOR3_CONFIG_SUBSAMPLE                (158)
#define AHB_ITEM_CHANGE_SENSOR3_SCENARIOINFO                    (159)
#define AHB_ITEM_CHANGE_SENSOR3_CROPSIZE                        (160)
#define AHB_ITEM_CHANGE_SENSOR3_BALANCED_AWB                    (161)
#define AHB_ITEM_CHANGE_SENSOR3_BRIGHTNESS                      (162)
#define AHB_ITEM_CHANGE_SENSOR3_CCM                             (163)
#define AHB_ITEM_CHANGE_SENSOR3_IQ_OTP_INFO                     (164)
#define AHB_ITEM_CHANGE_SENSOR3_VALID_EXPOSURE_TIME             (165)
#define AHB_ITEM_CHANGE_SENSOR3_VALID_AD_GAIN                   (166)
#define AHB_ITEM_CHANGE_SENSOR3_COLOR_TEMPERATURE               (167)
#define AHB_ITEM_CHANGE_SENSOR3_SCENE                           (168)
#define AHB_ITEM_CHANGE_SENSOR3_FLASH                           (169)
#define AHB_ITEM_CHANGE_SENSOR3_RAW_FORMAT                      (170)
#define AHB_ITEM_CHANGE_SENSOR3_ADAPTIVE_SHAD_BUF_INFO          (171)
#define AHB_ITEM_CHANGE_SENSOR3_IQ_INFO                         (172)
#define AHB_ITEM_CHANGE_SENSOR3_ISP_D_GAIN                      (173)
#define AHB_ITEM_CHANGE_SENSOR3_Y_OFFSET                        (174)
#define AHB_ITEM_CHANGE_SENSOR3_IQ_PARAM_IDX                    (175)
#define AHB_ITEM_SYS_BOOT_FINISH_INT_EN                         (176)
#define AHB_ITEM_SYS_CMD_FINISH_INT_EN                          (177)
#define AHB_ITEM_SYS_IP_ERROR_INT_EN                            (178)
#define AHB_ITEM_SYS_BOOT_FINISH_INT                            (179)
#define AHB_ITEM_SYS_CMD_FINISH_INT                             (180)
#define AHB_ITEM_SYS_IP_ERROR_INT                               (181)
#define AHB_ITEM_SENSOR1_CONFIG_ADDR                            (182)
#define AHB_ITEM_SENSOR1_YUY2_USER_DEF_ADDR                     (183)
#define AHB_ITEM_SENSOR1_TONEMAP_DATA_ADDR                      (184)
#define AHB_ITEM_SENSOR1_MOTION_DATA_ADDR                       (185)
#define AHB_ITEM_SENSOR1_OUT_TYPE_IMG1                          (186)
#define AHB_ITEM_SENSOR1_OUT_TYPE_IMG2                          (187)
#define AHB_ITEM_SENSOR1_OUT_TYPE_IMG3                          (188)
#define AHB_ITEM_SENSOR1_PATH_MODE                              (189)
#define AHB_ITEM_SENSOR1_RAW_OUT_TYPE                           (190)
#define AHB_ITEM_SENSOR1_OUT_IMG1_WIDTH                         (191)
#define AHB_ITEM_SENSOR1_OUT_IMG1_HEIGHT                        (192)
#define AHB_ITEM_SENSOR1_OUT_IMG2_WIDTH                         (193)
#define AHB_ITEM_SENSOR1_OUT_IMG2_HEIGHT                        (194)
#define AHB_ITEM_SENSOR1_OUT_IMG3_WIDTH                         (195)
#define AHB_ITEM_SENSOR1_OUT_IMG3_HEIGHT                        (196)
#define AHB_ITEM_SENSOR1_OUT_IMG1_LINE_OFFSET                   (197)
#define AHB_ITEM_SENSOR1_OUT_IMG2_LINE_OFFSET                   (198)
#define AHB_ITEM_SENSOR1_OUT_IMG3_LINE_OFFSET                   (199)
#define AHB_ITEM_SENSOR1_OUT_IMG1_EN                            (200)
#define AHB_ITEM_SENSOR1_OUT_IMG2_EN                            (201)
#define AHB_ITEM_SENSOR1_OUT_IMG3_EN                            (202)
#define AHB_ITEM_SENSOR1_OUT_STATISTICS_EN                      (203)
#define AHB_ITEM_SENSOR1_OUT_IMG1_BUF_NUM                       (204)
#define AHB_ITEM_SENSOR1_OUT_IMG2_BUF_NUM                       (205)
#define AHB_ITEM_SENSOR1_OUT_IMG3_BUF_NUM                       (206)
#define AHB_ITEM_SENSOR1_OUT_STATISTICS_BUF_NUM                 (207)
#define AHB_ITEM_SENSOR1_OUT_RAW_BUF_NUM                        (208)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR1                         (209)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR2                         (210)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR3                         (211)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR4                         (212)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR1                         (213)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR2                         (214)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR3                         (215)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR4                         (216)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR1                         (217)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR2                         (218)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR3                         (219)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR4                         (220)
#define AHB_ITEM_SENSOR1_OUT_STATISTICS_ADDR1                   (221)
#define AHB_ITEM_SENSOR1_OUT_STATISTICS_ADDR2                   (222)
#define AHB_ITEM_SENSOR1_OUT_STATISTICS_ADDR3                   (223)
#define AHB_ITEM_SENSOR1_OUT_STATISTICS_ADDR4                   (224)
#define AHB_ITEM_SENSOR1_OUT_AF_STATISTICS_ADDR1                (225)
#define AHB_ITEM_SENSOR1_OUT_AF_STATISTICS_ADDR2                (226)
#define AHB_ITEM_SENSOR1_OUT_AF_STATISTICS_ADDR3                (227)
#define AHB_ITEM_SENSOR1_OUT_AF_STATISTICS_ADDR4                (228)
#define AHB_ITEM_SENSOR1_OUT_RAW_ADD1                           (229)
#define AHB_ITEM_SENSOR1_OUT_RAW_ADD2                           (230)
#define AHB_ITEM_SENSOR1_OUT_RAW_ADD3                           (231)
#define AHB_ITEM_SENSOR1_OUT_RAW_ADD4                           (232)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR1_ISP1                    (233)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR2_ISP1                    (234)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR3_ISP1                    (235)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR4_ISP1                    (236)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR1_ISP1                    (237)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR2_ISP1                    (238)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR3_ISP1                    (239)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR4_ISP1                    (240)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR1_ISP1                    (241)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR2_ISP1                    (242)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR3_ISP1                    (243)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR4_ISP1                    (244)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR1_NV12_UV                 (245)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR2_NV12_UV                 (246)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR3_NV12_UV                 (247)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR4_NV12_UV                 (248)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR1_NV12_UV                 (249)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR2_NV12_UV                 (250)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR3_NV12_UV                 (251)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR4_NV12_UV                 (252)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR1_NV12_UV                 (253)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR2_NV12_UV                 (254)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR3_NV12_UV                 (255)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR4_NV12_UV                 (256)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR1_NV12_UV_ISP1            (257)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR2_NV12_UV_ISP1            (258)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR3_NV12_UV_ISP1            (259)
#define AHB_ITEM_SENSOR1_OUT_IMG1_ADDR4_NV12_UV_ISP1            (260)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR1_NV12_UV_ISP1            (261)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR2_NV12_UV_ISP1            (262)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR3_NV12_UV_ISP1            (263)
#define AHB_ITEM_SENSOR1_OUT_IMG2_ADDR4_NV12_UV_ISP1            (264)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR1_NV12_UV_ISP1            (265)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR2_NV12_UV_ISP1            (266)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR3_NV12_UV_ISP1            (267)
#define AHB_ITEM_SENSOR1_OUT_IMG3_ADDR4_NV12_UV_ISP1            (268)
#define AHB_ITEM_SENSOR1_CONTRAST                               (269)
#define AHB_ITEM_SENSOR1_SHARPNESS                              (270)
#define AHB_ITEM_SENSOR1_SATURATION                             (271)
#define AHB_ITEM_SENSOR1_SPECIAL_EFFECT                         (272)
#define AHB_ITEM_SENSOR1_TONEMAP_MODE                           (273)
#define AHB_ITEM_SENSOR1_YUY2_FORMAT                            (274)
#define AHB_ITEM_SENSOR1_SHADING                                (275)
#define AHB_ITEM_SENSOR1_FAST_CONVERGE_SETTING                  (276)
#define AHB_ITEM_SENSOR1_BRIGHTNESS                             (277)
#define AHB_ITEM_SENSOR1_SCENE                                  (278)
#define AHB_ITEM_SENSOR1_FLASH                                  (279)
#define AHB_ITEM_SENSOR1_3ADLDSEQ_ADDR                          (280)
#define AHB_ITEM_SENSOR1_CONFIG3A_ADDR                          (281)
#define AHB_ITEM_SENSOR1_DZOOMINFO_ADDR                         (282)
#define AHB_ITEM_SENSOR1_QMERGE_ADDR                            (283)
#define AHB_ITEM_SENSOR1_SHADING_ADDR                           (284)
#define AHB_ITEM_SENSOR1_CBC_MAP_ADDR                           (285)
#define AHB_ITEM_SENSOR1_DETECTEDAWB_R                          (286)
#define AHB_ITEM_SENSOR1_DETECTEDAWB_GR                         (287)
#define AHB_ITEM_SENSOR1_DETECTEDAWB_GB                         (288)
#define AHB_ITEM_SENSOR1_DETECTEDAWB_B                          (289)
#define AHB_ITEM_SENSOR1_DETECTEDGAIN_ISO                       (290)
#define AHB_ITEM_SENSOR1_BALANCEDAWB_R                          (291)
#define AHB_ITEM_SENSOR1_BALANCEDAWB_GR                         (292)
#define AHB_ITEM_SENSOR1_BALANCEDAWB_GB                         (293)
#define AHB_ITEM_SENSOR1_BALANCEDAWB_B                          (294)
#define AHB_ITEM_SENSOR1_DEBUG_INFO_ADDR                        (295)
#define AHB_ITEM_SENSOR1_CCM_INFO_ADDR                          (296)
#define AHB_ITEM_SENSOR1_IQ_OTP_INFO_ADDR                       (297)
#define AHB_ITEM_SENSOR1_VALID_EXPOSURE_TIME                    (298)
#define AHB_ITEM_SENSOR1_VALID_AD_GAIN                          (299)
#define AHB_ITEM_SENSOR1_COLOR_TEMPERATURE                      (300)
#define AHB_ITEM_SENSOR1_BRIGHTNESS_SETTING_ADDR                (301)
#define AHB_ITEM_SENSOR1_RAW_FRAME_RATE                         (302)
#define AHB_ITEM_SENSOR1_RAW_DUMP_FORMAT                        (303)
#define AHB_ITEM_SENSOR1_RAW_INFO_ADDR                          (304)
#define AHB_ITEM_SENSOR1_PROC_STILL_ADDR                        (305)
#define AHB_ITEM_SENSOR1_AD_SHAD_BUF_ADDR                       (306)
#define AHB_ITEM_SENSOR1_IQ_INFO_ADDR                           (307)
#define AHB_ITEM_SENSOR1_ISP_D_GAIN_ADDR                        (308)
#define AHB_ITEM_SENSOR1_Y_OFFSET                               (309)
#define AHB_ITEM_SENSOR1_IQ_PARAM_IDX_LV                        (310)
#define AHB_ITEM_SENSOR1_IQ_PARAM_IDX_VIDEO                     (311)
#define AHB_ITEM_SENSOR1_IQ_PARAM_IDX_STILL                     (312)
#define AHB_ITEM_SENSOR2_YUY2_USER_DEF_ADDR                     (313)
#define AHB_ITEM_SENSOR2_TONEMAP_DATA_ADDR                      (314)
#define AHB_ITEM_SENSOR2_MOTION_DATA_ADDR                       (315)
#define AHB_ITEM_SENSOR2_OUT_TYPE_IMG1                          (316)
#define AHB_ITEM_SENSOR2_OUT_TYPE_IMG2                          (317)
#define AHB_ITEM_SENSOR2_OUT_TYPE_IMG3                          (318)
#define AHB_ITEM_SENSOR2_PATH_MODE                              (319)
#define AHB_ITEM_SENSOR2_OUT_IMG1_WIDTH                         (320)
#define AHB_ITEM_SENSOR2_OUT_IMG1_HEIGHT                        (321)
#define AHB_ITEM_SENSOR2_OUT_IMG2_WIDTH                         (322)
#define AHB_ITEM_SENSOR2_OUT_IMG2_HEIGHT                        (323)
#define AHB_ITEM_SENSOR2_OUT_IMG3_WIDTH                         (324)
#define AHB_ITEM_SENSOR2_OUT_IMG3_HEIGHT                        (325)
#define AHB_ITEM_SENSOR2_OUT_IMG1_LINE_OFFSET                   (326)
#define AHB_ITEM_SENSOR2_OUT_IMG2_LINE_OFFSET                   (327)
#define AHB_ITEM_SENSOR2_OUT_IMG3_LINE_OFFSET                   (328)
#define AHB_ITEM_SENSOR2_OUT_IMG1_EN                            (329)
#define AHB_ITEM_SENSOR2_OUT_IMG2_EN                            (330)
#define AHB_ITEM_SENSOR2_OUT_IMG3_EN                            (331)
#define AHB_ITEM_SENSOR2_OUT_STATISTICS_EN                      (332)
#define AHB_ITEM_SENSOR2_OUT_IMG1_BUF_NUM                       (333)
#define AHB_ITEM_SENSOR2_OUT_IMG2_BUF_NUM                       (334)
#define AHB_ITEM_SENSOR2_OUT_IMG3_BUF_NUM                       (335)
#define AHB_ITEM_SENSOR2_OUT_STATISTICS_BUF_NUM                 (336)
#define AHB_ITEM_SENSOR2_OUT_IMG1_ADDR1                         (337)
#define AHB_ITEM_SENSOR2_OUT_IMG1_ADDR2                         (338)
#define AHB_ITEM_SENSOR2_OUT_IMG1_ADDR3                         (339)
#define AHB_ITEM_SENSOR2_OUT_IMG1_ADDR4                         (340)
#define AHB_ITEM_SENSOR2_OUT_IMG2_ADDR1                         (341)
#define AHB_ITEM_SENSOR2_OUT_IMG2_ADDR2                         (342)
#define AHB_ITEM_SENSOR2_OUT_IMG2_ADDR3                         (343)
#define AHB_ITEM_SENSOR2_OUT_IMG2_ADDR4                         (344)
#define AHB_ITEM_SENSOR2_OUT_IMG3_ADDR1                         (345)
#define AHB_ITEM_SENSOR2_OUT_IMG3_ADDR2                         (346)
#define AHB_ITEM_SENSOR2_OUT_IMG3_ADDR3                         (347)
#define AHB_ITEM_SENSOR2_OUT_IMG3_ADDR4                         (348)
#define AHB_ITEM_SENSOR2_OUT_STATISTICS_ADDR1                   (349)
#define AHB_ITEM_SENSOR2_OUT_STATISTICS_ADDR2                   (350)
#define AHB_ITEM_SENSOR2_OUT_STATISTICS_ADDR3                   (351)
#define AHB_ITEM_SENSOR2_OUT_STATISTICS_ADDR4                   (352)
#define AHB_ITEM_SENSOR2_OUT_AF_STATISTICS_ADDR1                (353)
#define AHB_ITEM_SENSOR2_OUT_AF_STATISTICS_ADDR2                (354)
#define AHB_ITEM_SENSOR2_OUT_AF_STATISTICS_ADDR3                (355)
#define AHB_ITEM_SENSOR2_OUT_AF_STATISTICS_ADDR4                (356)
#define AHB_ITEM_SENSOR2_OUT_IMG1_ADDR1_NV12_UV                 (357)
#define AHB_ITEM_SENSOR2_OUT_IMG1_ADDR2_NV12_UV                 (358)
#define AHB_ITEM_SENSOR2_OUT_IMG1_ADDR3_NV12_UV                 (359)
#define AHB_ITEM_SENSOR2_OUT_IMG1_ADDR4_NV12_UV                 (360)
#define AHB_ITEM_SENSOR2_OUT_IMG2_ADDR1_NV12_UV                 (361)
#define AHB_ITEM_SENSOR2_OUT_IMG2_ADDR2_NV12_UV                 (362)
#define AHB_ITEM_SENSOR2_OUT_IMG2_ADDR3_NV12_UV                 (363)
#define AHB_ITEM_SENSOR2_OUT_IMG2_ADDR4_NV12_UV                 (364)
#define AHB_ITEM_SENSOR2_OUT_IMG3_ADDR1_NV12_UV                 (365)
#define AHB_ITEM_SENSOR2_OUT_IMG3_ADDR2_NV12_UV                 (366)
#define AHB_ITEM_SENSOR2_OUT_IMG3_ADDR3_NV12_UV                 (367)
#define AHB_ITEM_SENSOR2_OUT_IMG3_ADDR4_NV12_UV                 (368)
#define AHB_ITEM_SENSOR2_CONTRAST                               (369)
#define AHB_ITEM_SENSOR2_SHARPNESS                              (370)
#define AHB_ITEM_SENSOR2_SATURATION                             (371)
#define AHB_ITEM_SENSOR2_SPECIAL_EFFECT                         (372)
#define AHB_ITEM_SENSOR2_TONEMAP_MODE                           (373)
#define AHB_ITEM_SENSOR2_YUY2_FORMAT                            (374)
#define AHB_ITEM_SENSOR2_SHADING                                (375)
#define AHB_ITEM_SENSOR2_FAST_CONVERGE_SETTING                  (376)
#define AHB_ITEM_SENSOR2_BRIGHTNESS                             (377)
#define AHB_ITEM_SENSOR2_SCENE                                  (378)
#define AHB_ITEM_SENSOR2_FLASH                                  (379)
#define AHB_ITEM_SENSOR2_3ADLDSEQ_ADDR                          (380)
#define AHB_ITEM_SENSOR2_CONFIG3A_ADDR                          (381)
#define AHB_ITEM_SENSOR2_DZOOMINFO_ADDR                         (382)
#define AHB_ITEM_SENSOR2_QMERGE_ADDR                            (383)
#define AHB_ITEM_SENSOR2_SHADING_ADDR                           (384)
#define AHB_ITEM_SENSOR2_CBC_MAP_ADDR                           (385)
#define AHB_ITEM_SENSOR2_DETECTEDAWB_R                          (386)
#define AHB_ITEM_SENSOR2_DETECTEDAWB_GR                         (387)
#define AHB_ITEM_SENSOR2_DETECTEDAWB_GB                         (388)
#define AHB_ITEM_SENSOR2_DETECTEDAWB_B                          (389)
#define AHB_ITEM_SENSOR2_DETECTEDGAIN_ISO                       (390)
#define AHB_ITEM_SENSOR2_BALANCEDAWB_R                          (391)
#define AHB_ITEM_SENSOR2_BALANCEDAWB_GR                         (392)
#define AHB_ITEM_SENSOR2_BALANCEDAWB_GB                         (393)
#define AHB_ITEM_SENSOR2_BALANCEDAWB_B                          (394)
#define AHB_ITEM_SENSOR2_DEBUG_INFO_ADDR                        (395)
#define AHB_ITEM_SENSOR2_CCM_INFO_ADDR                          (396)
#define AHB_ITEM_SENSOR2_IQ_OTP_INFO_ADDR                       (397)
#define AHB_ITEM_SENSOR2_VALID_EXPOSURE_TIME                    (398)
#define AHB_ITEM_SENSOR2_VALID_AD_GAIN                          (399)
#define AHB_ITEM_SENSOR2_COLOR_TEMPERATURE                      (400)
#define AHB_ITEM_SENSOR2_BRIGHTNESS_SETTING_ADDR                (401)
#define AHB_ITEM_SENSOR2_RAW_DUMP_FORMAT                        (402)
#define AHB_ITEM_SENSOR2_AD_SHAD_BUF_ADDR                       (403)
#define AHB_ITEM_SENSOR2_IQ_INFO_ADDR                           (404)
#define AHB_ITEM_SENSOR2_ISP_D_GAIN_ADDR                        (405)
#define AHB_ITEM_SENSOR2_Y_OFFSET                               (406)
#define AHB_ITEM_SENSOR2_IQ_PARAM_IDX_LV                        (407)
#define AHB_ITEM_SENSOR2_IQ_PARAM_IDX_VIDEO                     (408)
#define AHB_ITEM_SENSOR2_IQ_PARAM_IDX_STILL                     (409)
#define AHB_ITEM_SENSOR3_YUY2_USER_DEF_ADDR                     (410)
#define AHB_ITEM_SENSOR3_TONEMAP_DATA_ADDR                      (411)
#define AHB_ITEM_SENSOR3_MOTION_DATA_ADDR                       (412)
#define AHB_ITEM_SENSOR3_OUT_TYPE_IMG1                          (413)
#define AHB_ITEM_SENSOR3_OUT_IMG1_WIDTH                         (414)
#define AHB_ITEM_SENSOR3_OUT_IMG1_HEIGHT                        (415)
#define AHB_ITEM_SENSOR3_OUT_IMG1_LINE_OFFSET                   (416)
#define AHB_ITEM_SENSOR3_OUT_IMG1_EN                            (417)
#define AHB_ITEM_SENSOR3_OUT_STATISTICS_EN                      (418)
#define AHB_ITEM_SENSOR3_OUT_IMG1_BUF_NUM                       (419)
#define AHB_ITEM_SENSOR3_OUT_STATISTICS_BUF_NUM                 (420)
#define AHB_ITEM_SENSOR3_OUT_IMG1_ADDR1                         (421)
#define AHB_ITEM_SENSOR3_OUT_IMG1_ADDR2                         (422)
#define AHB_ITEM_SENSOR3_OUT_IMG1_ADDR3                         (423)
#define AHB_ITEM_SENSOR3_OUT_IMG1_ADDR4                         (424)
#define AHB_ITEM_SENSOR3_OUT_STATISTICS_ADDR1                   (425)
#define AHB_ITEM_SENSOR3_OUT_STATISTICS_ADDR2                   (426)
#define AHB_ITEM_SENSOR3_OUT_STATISTICS_ADDR3                   (427)
#define AHB_ITEM_SENSOR3_OUT_STATISTICS_ADDR4                   (428)
#define AHB_ITEM_SENSOR3_OUT_AF_STATISTICS_ADDR1                (429)
#define AHB_ITEM_SENSOR3_OUT_AF_STATISTICS_ADDR2                (430)
#define AHB_ITEM_SENSOR3_OUT_AF_STATISTICS_ADDR3                (431)
#define AHB_ITEM_SENSOR3_OUT_AF_STATISTICS_ADDR4                (432)
#define AHB_ITEM_SENSOR3_OUT_IMG1_ADDR1_NV12_UV                 (433)
#define AHB_ITEM_SENSOR3_OUT_IMG1_ADDR2_NV12_UV                 (434)
#define AHB_ITEM_SENSOR3_OUT_IMG1_ADDR3_NV12_UV                 (435)
#define AHB_ITEM_SENSOR3_OUT_IMG1_ADDR4_NV12_UV                 (436)
#define AHB_ITEM_SENSOR3_CONTRAST                               (437)
#define AHB_ITEM_SENSOR3_SHARPNESS                              (438)
#define AHB_ITEM_SENSOR3_SATURATION                             (439)
#define AHB_ITEM_SENSOR3_SPECIAL_EFFECT                         (440)
#define AHB_ITEM_SENSOR3_TONEMAP_MODE                           (441)
#define AHB_ITEM_SENSOR3_YUY2_FORMAT                            (442)
#define AHB_ITEM_SENSOR3_SHADING                                (443)
#define AHB_ITEM_SENSOR3_FAST_CONVERGE_SETTING                  (444)
#define AHB_ITEM_SENSOR3_BRIGHTNESS                             (445)
#define AHB_ITEM_SENSOR3_SCENE                                  (446)
#define AHB_ITEM_SENSOR3_FLASH                                  (447)
#define AHB_ITEM_SENSOR3_3ADLDSEQ_ADDR                          (448)
#define AHB_ITEM_SENSOR3_CONFIG3A_ADDR                          (449)
#define AHB_ITEM_SENSOR3_DZOOMINFO_ADDR                         (450)
#define AHB_ITEM_SENSOR3_QMERGE_ADDR                            (451)
#define AHB_ITEM_SENSOR3_SHADING_ADDR                           (452)
#define AHB_ITEM_SENSOR3_CBC_MAP_ADDR                           (453)
#define AHB_ITEM_SENSOR3_DETECTEDAWB_R                          (454)
#define AHB_ITEM_SENSOR3_DETECTEDAWB_GR                         (455)
#define AHB_ITEM_SENSOR3_DETECTEDAWB_GB                         (456)
#define AHB_ITEM_SENSOR3_DETECTEDAWB_B                          (457)
#define AHB_ITEM_SENSOR3_DETECTEDGAIN_ISO                       (458)
#define AHB_ITEM_SENSOR3_BALANCEDAWB_R                          (459)
#define AHB_ITEM_SENSOR3_BALANCEDAWB_GR                         (460)
#define AHB_ITEM_SENSOR3_BALANCEDAWB_GB                         (461)
#define AHB_ITEM_SENSOR3_BALANCEDAWB_B                          (462)
#define AHB_ITEM_SENSOR3_DEBUG_INFO_ADDR                        (463)
#define AHB_ITEM_SENSOR3_CCM_INFO_ADDR                          (464)
#define AHB_ITEM_SENSOR3_IQ_OTP_INFO_ADDR                       (465)
#define AHB_ITEM_SENSOR3_VALID_EXPOSURE_TIME                    (466)
#define AHB_ITEM_SENSOR3_VALID_AD_GAIN                          (467)
#define AHB_ITEM_SENSOR3_COLOR_TEMPERATURE                      (468)
#define AHB_ITEM_SENSOR3_BRIGHTNESS_SETTING_ADDR                (469)
#define AHB_ITEM_SENSOR3_RAW_DUMP_FORMAT                        (470)
#define AHB_ITEM_SENSOR3_AD_SHAD_BUF_ADDR                       (471)
#define AHB_ITEM_SENSOR3_IQ_INFO_ADDR                           (472)
#define AHB_ITEM_SENSOR3_ISP_D_GAIN_ADDR                        (473)
#define AHB_ITEM_SENSOR3_Y_OFFSET                               (474)
#define AHB_ITEM_SENSOR3_IQ_PARAM_IDX_LV                        (475)
#define AHB_ITEM_OVERLAP_PIXEL_NUM                              (476)
#define AHB_ITEM_ISP_CHIP_ID                                    (477)
#define AHB_ITEM_SENSOR1_OUT_IMG1_DONE_INT_EN                   (478)
#define AHB_ITEM_SENSOR1_OUT_IMG2_DONE_INT_EN                   (479)
#define AHB_ITEM_SENSOR1_OUT_IMG3_DONE_INT_EN                   (480)
#define AHB_ITEM_SENSOR1_3A_DONE_INT_EN                         (481)
#define AHB_ITEM_SENSOR1_AF_DONE_INT_EN                         (482)
#define AHB_ITEM_SENSOR1_ISP_SOF_INT_EN                         (483)
#define AHB_ITEM_SENSOR1_3A_LINEMEET_INT_EN                     (484)
#define AHB_ITEM_SENSOR1_STILL_PROC_START_INT_EN                (485)
#define AHB_ITEM_SENSOR1_RAW_DONE_INT_EN                        (486)
#define AHB_ITEM_SENSOR2_OUT_IMG1_DONE_INT_EN                   (487)
#define AHB_ITEM_SENSOR2_OUT_IMG2_DONE_INT_EN                   (488)
#define AHB_ITEM_SENSOR2_OUT_IMG3_DONE_INT_EN                   (489)
#define AHB_ITEM_SENSOR2_3A_DONE_INT_EN                         (490)
#define AHB_ITEM_SENSOR2_AF_DONE_INT_EN                         (491)
#define AHB_ITEM_SENSOR2_ISP_SOF_INT_EN                         (492)
#define AHB_ITEM_SENSOR2_3A_LINEMEET_INT_EN                     (493)
#define AHB_ITEM_SENSOR3_OUT_IMG_DONE_INT_EN                    (494)
#define AHB_ITEM_SENSOR3_3A_DONE_INT_EN                         (495)
#define AHB_ITEM_SENSOR3_AF_DONE_INT_EN                         (496)
#define AHB_ITEM_SENSOR3_ISP_SOF_INT_EN                         (497)
#define AHB_ITEM_SENSOR3_3A_LINEMEET_INT_EN                     (498)
#define AHB_ITEM_SENSOR1_OUT_IMG1_DONE_INT                      (499)
#define AHB_ITEM_SENSOR1_OUT_IMG2_DONE_INT                      (500)
#define AHB_ITEM_SENSOR1_OUT_IMG3_DONE_INT                      (501)
#define AHB_ITEM_SENSOR1_3A_DONE_INT                            (502)
#define AHB_ITEM_SENSOR1_AF_DONE_INT                            (503)
#define AHB_ITEM_SENSOR1_ISP_SOF_INT                            (504)
#define AHB_ITEM_SENSOR1_3A_LINEMEET_INT                        (505)
#define AHB_ITEM_SENSOR1_STILL_PROC_START_INT                   (506)
#define AHB_ITEM_SENSOR1_RAW_DONE_INT                           (507)
#define AHB_ITEM_SENSOR2_OUT_IMG1_DONE_INT                      (508)
#define AHB_ITEM_SENSOR2_OUT_IMG2_DONE_INT                      (509)
#define AHB_ITEM_SENSOR2_OUT_IMG3_DONE_INT                      (510)
#define AHB_ITEM_SENSOR2_3A_DONE_INT                            (511)
#define AHB_ITEM_SENSOR2_AF_DONE_INT                            (512)
#define AHB_ITEM_SENSOR2_ISP_SOF_INT                            (513)
#define AHB_ITEM_SENSOR2_3A_LINEMEET_INT                        (514)
#define AHB_ITEM_SENSOR3_OUT_IMG_DONE_INT                       (515)
#define AHB_ITEM_SENSOR3_3A_DONE_INT                            (516)
#define AHB_ITEM_SENSOR3_AF_DONE_INT                            (517)
#define AHB_ITEM_SENSOR3_ISP_SOF_INT                            (518)
#define AHB_ITEM_SENSOR3_3A_LINEMEET_INT                        (519)
#define AHB_ITEM_MAX                                            (520)



/*
 *@typedef HAL_AHB_GROUP_INT_ID
 *@brief AHB group interrupt ID
 */
enum hal_ahb_group_int_id {
	HAL_AHB_GROUP_INT_00  = MASK_AHB_REG_FD_GOURP_00_INT_EN,
	HAL_AHB_GROUP_INT_01  = MASK_AHB_REG_FD_GOURP_01_INT_EN,
	HAL_AHB_GROUP_INT_02  = MASK_AHB_REG_FD_GOURP_02_INT_EN,
	HAL_AHB_GROUP_INT_03  = MASK_AHB_REG_FD_GOURP_03_INT_EN,
	HAL_AHB_GROUP_INT_04  = MASK_AHB_REG_FD_GOURP_04_INT_EN,
	HAL_AHB_GROUP_INT_05  = MASK_AHB_REG_FD_GOURP_05_INT_EN,
	HAL_AHB_GROUP_INT_06  = MASK_AHB_REG_FD_GOURP_06_INT_EN,
	HAL_AHB_GROUP_INT_07  = MASK_AHB_REG_FD_GOURP_07_INT_EN,
	HAL_AHB_GROUP_INT_08  = MASK_AHB_REG_FD_GOURP_08_INT_EN,
	HAL_AHB_GROUP_INT_09  = MASK_AHB_REG_FD_GOURP_09_INT_EN,
	HAL_AHB_GROUP_INT_10  = MASK_AHB_REG_FD_GOURP_10_INT_EN,
	HAL_AHB_GROUP_INT_11  = MASK_AHB_REG_FD_GOURP_11_INT_EN,
	HAL_AHB_GROUP_INT_12  = MASK_AHB_REG_FD_GOURP_12_INT_EN,
	HAL_AHB_GROUP_INT_13  = MASK_AHB_REG_FD_GOURP_13_INT_EN,
	HAL_AHB_GROUP_INT_14  = MASK_AHB_REG_FD_GOURP_14_INT_EN,
	HAL_AHB_GROUP_INT_15  = MASK_AHB_REG_FD_GOURP_15_INT_EN,
	HAL_AHB_GROUP_INT_16  = MASK_AHB_REG_FD_GOURP_16_INT_EN,
	HAL_AHB_GROUP_INT_17  = MASK_AHB_REG_FD_GOURP_17_INT_EN,
	HAL_AHB_GROUP_INT_18  = MASK_AHB_REG_FD_GOURP_18_INT_EN,
	HAL_AHB_GROUP_INT_19  = MASK_AHB_REG_FD_GOURP_19_INT_EN,
	HAL_AHB_GROUP_INT_20  = MASK_AHB_REG_FD_GOURP_20_INT_EN,
	HAL_AHB_GROUP_INT_21  = MASK_AHB_REG_FD_GOURP_21_INT_EN,
	HAL_AHB_GROUP_INT_22  = MASK_AHB_REG_FD_GOURP_22_INT_EN,
	HAL_AHB_GROUP_INT_23  = MASK_AHB_REG_FD_GOURP_23_INT_EN,
	HAL_AHB_GROUP_INT_24  = MASK_AHB_REG_FD_GOURP_24_INT_EN,
	HAL_AHB_GROUP_INT_25  = MASK_AHB_REG_FD_GOURP_25_INT_EN,
	HAL_AHB_GROUP_INT_26  = MASK_AHB_REG_FD_GOURP_26_INT_EN,
	HAL_AHB_GROUP_INT_27  = MASK_AHB_REG_FD_GOURP_27_INT_EN,
	HAL_AHB_GROUP_INT_28  = MASK_AHB_REG_FD_GOURP_28_INT_EN,
	HAL_AHB_GROUP_INT_29  = MASK_AHB_REG_FD_GOURP_29_INT_EN,
	HAL_AHB_GROUP_INT_30  = MASK_AHB_REG_FD_GOURP_30_INT_EN,
	HAL_AHB_GROUP_INT_31  = MASK_AHB_REG_FD_GOURP_31_INT_EN,

	HAL_AHB_GROUP_INT_ALL = HAL_AHB_GROUP_INT_00 |
							HAL_AHB_GROUP_INT_01 |
							HAL_AHB_GROUP_INT_02 |
							HAL_AHB_GROUP_INT_03 |
							HAL_AHB_GROUP_INT_04 |
							HAL_AHB_GROUP_INT_05 |
							HAL_AHB_GROUP_INT_06 |
							HAL_AHB_GROUP_INT_07 |
							HAL_AHB_GROUP_INT_08 |
							HAL_AHB_GROUP_INT_09 |
							HAL_AHB_GROUP_INT_10 |
							HAL_AHB_GROUP_INT_11 |
							HAL_AHB_GROUP_INT_12 |
							HAL_AHB_GROUP_INT_13 |
							HAL_AHB_GROUP_INT_14 |
							HAL_AHB_GROUP_INT_15 |
							HAL_AHB_GROUP_INT_16 |
							HAL_AHB_GROUP_INT_17 |
							HAL_AHB_GROUP_INT_18 |
							HAL_AHB_GROUP_INT_19 |
							HAL_AHB_GROUP_INT_20 |
							HAL_AHB_GROUP_INT_21 |
							HAL_AHB_GROUP_INT_22 |
							HAL_AHB_GROUP_INT_23 |
							HAL_AHB_GROUP_INT_24 |
							HAL_AHB_GROUP_INT_25 |
							HAL_AHB_GROUP_INT_26 |
							HAL_AHB_GROUP_INT_27 |
							HAL_AHB_GROUP_INT_28 |
							HAL_AHB_GROUP_INT_29 |
							HAL_AHB_GROUP_INT_30 |
							HAL_AHB_GROUP_INT_31
};

/*
 *@typedef HAL_AHB_ERR_INT_ID
 *@brief AHB error interrupt ID
 */
enum hal_ahb_err_int_id {
	/* ahb protocol timeout err, response over 16 cycle */
	HAL_AHB_ERR_INT_TIMEOUT_ERR  = MASK_AHB_REG_FD_AHB_TIMEOUT_ERR_EN,
	/* ahb protocol alignment err, need 4B alignment */
	HAL_AHB_ERR_INT_ALIGN_ERR = MASK_AHB_REG_FD_AHB_ALIGN_ERR_EN,
	/* ahb access over register max offset */
	HAL_AHB_ERR_INT_OVERFLOW_ERR =
	MASK_AHB_REG_FD_AHB_OVERFLOW_ERR_EN,
	/* ahb access protected range */
	HAL_AHB_ERR_INT_PROTECT_ERR = MASK_AHB_REG_FD_AHB_PROTECT_ERR_EN,

	HAL_AHB_ERR_INT_ALL = HAL_AHB_ERR_INT_TIMEOUT_ERR  |
				HAL_AHB_ERR_INT_ALIGN_ERR    |
				HAL_AHB_ERR_INT_OVERFLOW_ERR |
				HAL_AHB_ERR_INT_PROTECT_ERR
};
/*
 * ////////////////////////////////////////////////
 *                   Structures Definition                     *
 * ///////////////////////////////////////////////
 */
struct ispahb_field_info {
	u16   entry_id;
	u8   shift_bit;
	u32  entry_mask;
};


/*
 * ////////////////////////////////////////////////
 *                    Public Function                         *
 * ////////////////////////////////////////////////
 */
extern u32 isp_open(u64 ahb_base_addr, u32 ahb_size, u32 *bootcode);
extern u32 isp_close(void);
extern u32 isp_get_field_value(u32 field_id);
extern void isp_set_field_value(u32 field_id, u32 value);
extern u32 isp_get_reg_value(u32 addr_offset);
extern void isp_set_reg_value(u32 addr_offset, u32 value);
extern void isp_set_hw_field_value(u32 entry, u32 mask, u32 value);
extern u32 isp_get_entry_value(u16 entry_id);
extern void isp_set_entry_value(u16 entry_id, u32 value);
extern void set_ahb_indirect(u32 addr, u32 wdata);
extern u32 get_ahb_indirect(u32 addr);
extern int get_isplog_flag(void);
extern void set_isplog_flag(int flag);
extern int isp_dev_append_response_raw(const char *fmt, ...);
extern int isp_dev_append_response(const char *fmt, ...);

#endif
