# UAPI Header export list
header-y += edid.h
header-y += sisfb.h
header-y += uvesafb.h
header-y += sprd_adf.h
header-y += sprd_isp.h
header-y += sensor_drv_k.h
header-y += sprd_dma_copy_k.h
header-y += sprd_rot_k.h
header-y += sprd_scale.h
header-y += sprd_img.h
header-y += sprd_scale_k.h
