# UAPI Header export list
header-y += edid.h
header-y += sisfb.h
header-y += uvesafb.h
header-y += isp_drv_kernel.h
header-y += sprd_isp_altek.h
header-y += sprd_sensor_k.h
header-y += sprd_img.h
header-y += sprd_dma_copy_k.h
header-y += sprd_cpp.h
header-y += sprd_jpg.h
header-y += sprd_isp_r6p10.h
header-y += sprd_isp_r6p10v2.h
header-y += sprd_isp_r6p11.h
header-y += sprd_isp_r6p12.h
header-y += sprd_isp_r6p91.h
header-y += sprd_isp_r8p1.h
header-y += sprd_rot_k.h
header-y += sprd_scale_k.h

