obj-y	+= mipi_dsih_api.o mipi_dsih_hal.o
obj-$(CONFIG_PHY_INTEL_SPRD) += mipi_dsih_dphy_intel_pll.o
obj-$(CONFIG_PHY_INTEL_SPRD) += mipi_dsih_dphy_intel.o
obj-$(CONFIG_PHY_SYNOPSYS_SPRD) += mipi_dsih_dphy.o
obj-$(CONFIG_PHY_MEGACORE_SPRD) += mipi_dsih_dphy_megacores_whale.o
