ifeq ($(CONFIG_FB_SPRD), y)
obj-y := sprdfb_main.o sprdfb_panel.o sprdfb_dispc.o
obj-y += sprdfb_dsi.o sprdfb_mipi.o sprdfb_mcu.o
obj-y += sprdfb_attr.o
obj-y += sprdfb_rgb.o
obj-y += sprdfb_mipi_panel.o
endif

obj-$(CONFIG_FB_SPRD) += dsi_1_21a/
