#
# Makefile for the light and prox drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_LIGHT_PROXIMITY_TMD22713T)	+= tmd22713.o
obj-$(CONFIG_LIGHT_PROXIMITY_RPR0400)	+= rpr0400_driver.o
obj-$(CONFIG_LIGHT_PROXIMITY_LTR553)    += ltr553.o
obj-$(CONFIG_LIGHT_PROXIMITY_STK3311)    += stk3x1x.o

