
sprd_dcam-objs := dcam_drv.o\
		dcam_core.o

obj-y += sprd_dcam.o




ccflags-y += -I$(srctree)/drivers/misc/sprd_camera/common
ccflags-y += -I$(srctree)/drivers/misc/sprd_camera/common/r3p0 \
		-I$(srctree)/drivers/misc/sprd_camera/sensor \
		-I$(srctree)/drivers/misc/sprd_camera/flash \
		-I$(srctree)/drivers/misc/sprd_camera/dcam/isp_r6p10 \
		-I$(srctree)/drivers/misc/sprd_camera/sensor/csi2/csi_sprd/receiver_r1p0
