/* ----------------------------------------------------------------------------
 *  Copyright (C) 2016 Intel Corporation

 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License Version 2
 *  as published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *  You should have received a copy of the GNU General Public License Version 2
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.

 ---------------------------------------------------------------------------*/

#ifndef _IRQ_HW_H_
#define _IRQ_HW_H

#define BIA_IOAPIC_OFFSET 25

#define UART0_IRQ (BIA_IOAPIC_OFFSET + 2)
#define UART1_IRQ (BIA_IOAPIC_OFFSET + 3)
#define UART2_IRQ (BIA_IOAPIC_OFFSET + 4)
#define UART3_IRQ (BIA_IOAPIC_OFFSET + 5)
#define UART4_IRQ (BIA_IOAPIC_OFFSET + 6)

#define SPI0_IRQ  (BIA_IOAPIC_OFFSET + 7)
#define SPI1_IRQ  (BIA_IOAPIC_OFFSET + 8)
#define SPI2_IRQ  (BIA_IOAPIC_OFFSET + 9)

#define SIM_IRQ   (BIA_IOAPIC_OFFSET + 10)

#define I2C0_IRQ  (BIA_IOAPIC_OFFSET + 11)
#define I2C1_IRQ  (BIA_IOAPIC_OFFSET + 12)
#define I2C2_IRQ  (BIA_IOAPIC_OFFSET + 13)
#define MBOX_TAR_AP_NOWAKEUP_IRQ  (BIA_IOAPIC_OFFSET + 14)
#define I2C4_IRQ  (BIA_IOAPIC_OFFSET + 15)
#define I2C5_IRQ  (BIA_IOAPIC_OFFSET + 16)

#define I2S0_IRQ  (BIA_IOAPIC_OFFSET + 17)
#define I2S1_IRQ  (BIA_IOAPIC_OFFSET + 18)
#define I2S2_IRQ  (BIA_IOAPIC_OFFSET + 19)
#define I2S3_IRQ  (BIA_IOAPIC_OFFSET + 20)

#define CAM_BM_IRQ      (BIA_IOAPIC_OFFSET + 21)
#define VSP_BM_IRQ      (BIA_IOAPIC_OFFSET + 22)
#define DMA_SEC_IRQ     (BIA_IOAPIC_OFFSET + 23)
#define ADI_IRQ         (BIA_IOAPIC_OFFSET + 24)
#define AON_DEF_SLV_IRQ (BIA_IOAPIC_OFFSET + 25)
#define AON_TMR_IRQ     (BIA_IOAPIC_OFFSET + 26)
#define AON_SYST_IRQ    (BIA_IOAPIC_OFFSET + 27)

#define MBOX_SRC_IRQ   (BIA_IOAPIC_OFFSET + 28)
#define MBOX_TAR_IRQ   (BIA_IOAPIC_OFFSET + 29)
#define I2C6_IRQ       (BIA_IOAPIC_OFFSET + 30)
#define PMIC_IRQ       (BIA_IOAPIC_OFFSET + 31)
/*NA 32*/
/*NA 33*/
/*NA 34*/
#define ITHM1_ALERT_IRQ (BIA_IOAPIC_OFFSET + 35)
#define USB2_IRQ     (BIA_IOAPIC_OFFSET + 36)
#define ISP_MAIN_CH1_IRQ (BIA_IOAPIC_OFFSET + 37)

#define SDIO0_IRQ (BIA_IOAPIC_OFFSET + 38)
#define SDIO1_IRQ (BIA_IOAPIC_OFFSET + 39)
#define SDIO2_IRQ (BIA_IOAPIC_OFFSET + 40)
#define SDIO3_IRQ  (BIA_IOAPIC_OFFSET + 41)
#define DMA_IRQ   (BIA_IOAPIC_OFFSET + 42)

#define BM_IRQ        (BIA_IOAPIC_OFFSET + 43)
/*NA 44*/
#define SPI3_IRQ      (BIA_IOAPIC_OFFSET + 45)
#define CE0_IRQ       (BIA_IOAPIC_OFFSET + 46)
#define CE1_IRQ       (BIA_IOAPIC_OFFSET + 47)
#define VBC_ADC23_IRQ (BIA_IOAPIC_OFFSET + 48)
#define VBC_ADC01_IRQ (BIA_IOAPIC_OFFSET + 49)

#define GPIO_IRQ (BIA_IOAPIC_OFFSET + 50)
#define KPD_IRQ  (BIA_IOAPIC_OFFSET + 51)
#define EIC_IRQ  (BIA_IOAPIC_OFFSET + 52)

#define TMR0_IRQ (BIA_IOAPIC_OFFSET + 53)
#define TMR1_IRQ (BIA_IOAPIC_OFFSET + 54)
#define TMR2_IRQ (BIA_IOAPIC_OFFSET + 55)
#define TMR3_IRQ (BIA_IOAPIC_OFFSET + 56)
#define TMR4_IRQ (BIA_IOAPIC_OFFSET + 57)
#define SYST_IRQ (BIA_IOAPIC_OFFSET + 58)

/*NA 59*/
#define ISP_LITE_CH0_IRQ         (BIA_IOAPIC_OFFSET + 60)
#define WDG_IRQ         (BIA_IOAPIC_OFFSET + 61)
#define DJTAG_IRQ       (BIA_IOAPIC_OFFSET + 62)
#define THM_IRQ         (BIA_IOAPIC_OFFSET + 63)
#define WTL_GSM_TX_IRQ  (BIA_IOAPIC_OFFSET + 64)
#define SEC_EIC_IRQ     (BIA_IOAPIC_OFFSET + 65)
#define GPU1_IRQ        (BIA_IOAPIC_OFFSET + 66)
#define GPU_IRQ        (BIA_IOAPIC_OFFSET + 67)
#define VSP_IRQ         (BIA_IOAPIC_OFFSET + 68)
#define DSIPLL_LOCK_STATUS_IRQ         (BIA_IOAPIC_OFFSET + 69)

#define ISP_PERFMON_IRQ  (BIA_IOAPIC_OFFSET + 70)
#define ISP_CH0_IRQ     (BIA_IOAPIC_OFFSET + 71)
#define CSI1_IRQ        (BIA_IOAPIC_OFFSET + 72)
#define CSI0_IRQ        (BIA_IOAPIC_OFFSET + 73)
#define CAM_IDI_SW_DONE_IRQ  (BIA_IOAPIC_OFFSET + 74)
#define JPG0_IRQ  (BIA_IOAPIC_OFFSET + 75)
#define DCAM1_IRQ (BIA_IOAPIC_OFFSET + 76)
#define DCAM0_IRQ (BIA_IOAPIC_OFFSET + 77)
#define ISP_LITE_CH1_IRQ  (BIA_IOAPIC_OFFSET + 78)
#define GSP0_IRQ  (BIA_IOAPIC_OFFSET + 79)
#define AON_DMA_CHN1_GRP1_SYNC_IRQ  (BIA_IOAPIC_OFFSET + 80)
#define AON_DMA_CHN2_GRP1_SYNC_IRQ  (BIA_IOAPIC_OFFSET + 81)
#define DSI0_IRQ  (BIA_IOAPIC_OFFSET + 82)
#define DSI1_IRQ  (BIA_IOAPIC_OFFSET + 83)
#define AON_DMA_CHN1_GRP2_SYNC_IRQ (BIA_IOAPIC_OFFSET + 84)
#define DISPC0_IRQ (BIA_IOAPIC_OFFSET + 85)

#define SEC_DMA_AON_IRQ   (BIA_IOAPIC_OFFSET + 86)
#define DMA_AON_IRQ (BIA_IOAPIC_OFFSET + 87)
#define AON_DMA_CHN2_GRP2_SYNC_IRQ (BIA_IOAPIC_OFFSET + 88)
#define PUB0_CTRL_IRQ   (BIA_IOAPIC_OFFSET + 89)
#define PUB0_AXI_BM_IRQ (BIA_IOAPIC_OFFSET + 90)
#define PUB0_DFI_BM_IRQ (BIA_IOAPIC_OFFSET + 91)

#define VBC_AUDRCD_AGCP_IRQ (BIA_IOAPIC_OFFSET + 92)
#define VBC_AUDPLY_AGCP_IRQ (BIA_IOAPIC_OFFSET + 93)
#define SRC44P1K_AGCP_IRQ   (BIA_IOAPIC_OFFSET + 94)
#define CPP_IRQ             (BIA_IOAPIC_OFFSET + 95)
#define SEC_GPIO_IRQ        (BIA_IOAPIC_OFFSET + 96)

#define BASEIA_DVFS_IRQ (BIA_IOAPIC_OFFSET + 97)

#define PCP_WDG_RST_IRQ        (BIA_IOAPIC_OFFSET + 98)
#define PCP_WDG_IRQ            (BIA_IOAPIC_OFFSET + 99)
#define DMC_MPU_IRQ		(BIA_IOAPIC_OFFSET + 100)
#define WTLCP_TG_WDG_IRQ       (BIA_IOAPIC_OFFSET + 101)
#define MEM_FW_PUB0_IRQ (BIA_IOAPIC_OFFSET + 102)
#define MEM_FW_AP_PUB0_IRQ (BIA_IOAPIC_OFFSET + 103)
#define AP_FW_IRQ (BIA_IOAPIC_OFFSET + 104)
#define MEM_FW_AON_IRAM_IRQ (BIA_IOAPIC_OFFSET + 105)
#define WTLLCP_LTE_WDG_RST_IRQ (BIA_IOAPIC_OFFSET + 106)

#define SLV_FW_AON_IRQ          (BIA_IOAPIC_OFFSET + 107)
#define DSIPLL_UNLOCK_STATUS_IRQ        (BIA_IOAPIC_OFFSET + 108)
#define ITHM1_OVERHEAT_IRQ   (BIA_IOAPIC_OFFSET + 109)
#define VOLTAGE0_BAD_IRQ     (BIA_IOAPIC_OFFSET + 110)
#define VOLTAGE0_CH_BUSY_IRQ (BIA_IOAPIC_OFFSET + 111)
#define VOLTAGE0_TRANS_IRQ   (BIA_IOAPIC_OFFSET + 112)
#define VOLTAGE1_BAD_IRQ     (BIA_IOAPIC_OFFSET + 113)
#define VOLTAGE1_CH_BUSY_IRQ (BIA_IOAPIC_OFFSET + 114)
#define VOLTAGE1_TRANS_IRQ   (BIA_IOAPIC_OFFSET + 115)

#define PUB0_DFS_ERROR_IRQ   (BIA_IOAPIC_OFFSET + 116)
#define BIA_WDG_RESET_IRQ   (BIA_IOAPIC_OFFSET + 117)
#define BIA_TMR_IRQ          (BIA_IOAPIC_OFFSET + 118)
#define ITHM0_OVERHEAT_IRQ        (BIA_IOAPIC_OFFSET + 119)
#define ITHM_ALERT_IRQ       (BIA_IOAPIC_OFFSET + 120)
#define DSI0_PLL_IRQ         (BIA_IOAPIC_OFFSET + 121)
#define CLK_32K_DET_IRQ      (BIA_IOAPIC_OFFSET + 122)
#define SEC_WDG_IRQ          (BIA_IOAPIC_OFFSET + 123)
/*NA 124*/
#define SEC_RTC_IRQ          (BIA_IOAPIC_OFFSET + 125)
#define SEC_TIMER0_IRQ       (BIA_IOAPIC_OFFSET + 126)
#define SEC_TIMER1_IRQ       (BIA_IOAPIC_OFFSET + 127)


/* defines below are only for pass compile sc9861 */
#define I2C3_IRQ  (BIA_IOAPIC_OFFSET + 230)
#define MPHY_HOP_OK_IRQ  (BIA_IOAPIC_OFFSET + 230)
#define GSP_MMU_IRQ (BIA_IOAPIC_OFFSET + 230)
#define VSP_MMU_IRQ (BIA_IOAPIC_OFFSET + 230)
#define DCAM2ISP_IF_IRQ (BIA_IOAPIC_OFFSET + 230)
#define UFS_IRQ       (BIA_IOAPIC_OFFSET + 230)
#define AGCP_MCDT_IRQ (BIA_IOAPIC_OFFSET + 230)
#define AGCP_DMA_IRQ  (BIA_IOAPIC_OFFSET + 230)
#define DISP_MMU_PF_IRQ (BIA_IOAPIC_OFFSET + 230)
#define CAM_MMU_PF_IRQ  (BIA_IOAPIC_OFFSET + 230)
#define CPP_MMU_PF_IRQ  (BIA_IOAPIC_OFFSET + 230)
#define GSP1_IRQ  (BIA_IOAPIC_OFFSET + 230)
#define DISPC1_IRQ (BIA_IOAPIC_OFFSET + 230)
#define PUB1_CTRL_IRQ   (BIA_IOAPIC_OFFSET + 230)
#define PUB1_AXI_BM_IRQ (BIA_IOAPIC_OFFSET + 230)
#define PUB1_DFI_BM_IRQ (BIA_IOAPIC_OFFSET + 230)
#define AGCP_DMA_CHN1_GRP1_IRQ (BIA_IOAPIC_OFFSET + 230)
#define AGCP_DMA_CHN2_GRP1_IRQ (BIA_IOAPIC_OFFSET + 230)
#define AGCP_DMA_CHN1_GRP2_IRQ (BIA_IOAPIC_OFFSET + 230)
#define AGCP_DMA_CHN2_GRP2_IRQ (BIA_IOAPIC_OFFSET + 230)
#define NOC_ERR_IRQ          (BIA_IOAPIC_OFFSET + 230)
#define STATALARM_IRQ        (BIA_IOAPIC_OFFSET + 230)
#define PUB1_DFS_ERROR_IRQ   (BIA_IOAPIC_OFFSET + 230)
#define VPP_DEINT_IRQ        (BIA_IOAPIC_OFFSET + 230)
#define DSI1_PLL_IRQ         (BIA_IOAPIC_OFFSET + 230)
#define GENERATION_PMU_IRQ   (BIA_IOAPIC_OFFSET + 230)

#endif
