obj-y += gsp_interface_sc9830.o gsp_interface_whale2.o gsp_interface_iwhale2.o gsp_interface_sc9833.o \
	 gsp_interface_isharkl2.o gsp_interface_sharklj1.o gsp_interface_sharkle.o gsp_interface_sharkl3.o \
	 gsp_interface_pike2.o gsp_interface_sharkl5.o