subdir-ccflags-y += -Idrivers/staging/android/
subdir-ccflags-y += -Idrivers/staging/android/ion

subdir-ccflags-y += -I$(src)
subdir-ccflags-y += -I$(src)/gsp_r1p1
subdir-ccflags-y += -I$(src)/gsp_r3p0
subdir-ccflags-y += -I$(src)/gsp_r4p0
subdir-ccflags-y += -I$(src)/gsp_lite_r1p0
subdir-ccflags-y += -I$(src)/gsp_r5p0
subdir-ccflags-y += -I$(src)/gsp_lite_r2p0
subdir-ccflags-y += -I$(src)/gsp_r6p0
subdir-ccflags-y += -I$(src)/gsp_lite_r3p0
subdir-ccflags-y += -I$(src)/gsp_interface


obj-y += gsp_r1p1/
obj-y += gsp_r3p0/
obj-y += gsp_r4p0/
obj-y += gsp_lite_r1p0/
obj-y += gsp_r5p0/
obj-y += gsp_lite_r2p0/
obj-y += gsp_r6p0/
obj-y += gsp_lite_r3p0/
obj-y += gsp_interface/
obj-y += gsp_core.o gsp_dev.o gsp_interface.o gsp_kcfg.o gsp_layer.o gsp_sync.o gsp_sysfs.o gsp_workqueue.o


