obj-$(CONFIG_MACH_SPX35LFPGA) += board-sp8830fpga.o
obj-$(CONFIG_MACH_PIKELFPGA) += board-sp8830fpga.o
obj-$(CONFIG_MACH_SP9630EA) += board-sp9630ea.o
obj-$(CONFIG_MACH_SP7731GEA) += board-sp7731gea.o ontim_device.o bootinfo.o
obj-$(CONFIG_MACH_SP7731GEA_HD2) += board-sp7731gea_hd2.o
obj-$(CONFIG_MACH_SP7731GEA_HD) += board-sp7731gea_hd.o  ontim_device.o bootinfo.o 
obj-$(CONFIG_MACH_SP7731GEA_HDR) += board-sp7731gea_hdr.o
obj-$(CONFIG_MACH_SP7731GEA_QHD) += board-sp7731gea_qhd.o
obj-$(CONFIG_MACH_SP7731GEPIKE) += board-sp7731gepike.o
obj-$(CONFIG_MACH_SP9630EA_4MOD) += board-sp9630ea_4mod.o
obj-$(CONFIG_MACH_COREPRIMELITE) += board-coreprimelite.o
obj-$(CONFIG_MACH_SP9630EA_3592M_3MOD) += board-sp9630ea_3592m_3mod.o
obj-$(CONFIG_MACH_PIKEAYOUNG2DTV) += board-pikeayoung2dtv.o

