#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

ccflags-y += -I$(srctree)/drivers/input/touchscreen/zte_touchscreen/focaltech_touch_V2_2/firmware_config/$(CONFIG_TS_FIRMWARE)/
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft5x46.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft5822.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft6336gu.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft8006.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft8606.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft8607.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft8716.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft8736.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft8006u.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft5422u.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft8719.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft8739.o
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2) += focaltech_upgrade_ft5452.o