subdir-ccflags-y += -Idrivers/staging/android/ion/
subdir-ccflags-y += -I$(src)/core/include
subdir-ccflags-y += -I$(src)/bridge/
subdir-ccflags-y += -I$(src)/drv/
subdir-ccflags-y += -I$(src)/drv/shark/

obj-y += drv/
obj-y += core/
