obj-$(CONFIG_SPRD_BUS_MONITOR) += sprd_ahb_bm.o sprd_axi_bm.o
obj-$(CONFIG_SPRD_AON_BUSMON) += sprd_aon_bm.o
ifeq ($(CONFIG_SPRD_SIPC),y)
	obj-$(CONFIG_SPRD_BM_DJTAG) += sprd_bm_djtag.o
endif
obj-$(CONFIG_SPRD_BUSMONITOR) += sprd_busmonitor.o
