#
# Makefile for spredtrum efuse drivers.
#
obj-$(CONFIG_OTP_SPRD) +=  sprd_otp.o
obj-$(CONFIG_OTP_SPRD_AP_EFUSE) += ap_efuse.o
obj-$(CONFIG_OTP_SPRD_AP_PUBLIC_EFUSE) += ap_public_efuse.o
obj-$(CONFIG_OTP_SPRD_AP_IEFUSE) += ap_iefuse.o
obj-$(CONFIG_OTP_SPRD_PMIC_EFUSE) += pmic_efuse.o


