#
# makefile for SPREADTRUM
#
obj-$(CONFIG_MARLIN2) += platform/
obj-$(CONFIG_INTEGRATED_MARLIN2_GE2) += platform/
obj-$(CONFIG_PACKER_SIMULATE) += packer_sim/
obj-$(CONFIG_SDIOM)		+= sdiom/
obj-$(CONFIG_MARLIN2_BT_SDIO)	+= bluetooth/
obj-$(CONFIG_RADIO_SC2332)	+= radio/
obj-$(CONFIG_GREENEYE2)	+= gnss/

