
ifeq ($(CONFIG_MACH_COREPRIMELITE),y)
obj-y += sensor_power_coreprimelite.o
else ifeq ($(CONFIG_MACH_TSHARK2TABE),y)
obj-y += sensor_power_tshark2tabe.o
else ifeq ($(CONFIG_MACH_GRANDPRIME3G_VE),y)
obj-y += sensor_power_grandprime3g_ve.o
else ifeq ($(CONFIG_MACH_SS_SHARKLT8),y)
obj-y += sensor_power_sharkl_t8.o
else ifeq ($(CONFIG_MACH_SS_SHARKLT8LIGHTSLEEP),y)
obj-y += sensor_power_sharkl_t8.o
else ifeq ($(CONFIG_MACH_GRANDPRIME_DTV),y)
obj-y += sensor_power_grandprime_dtv.o
else ifeq ($(CONFIG_MACH_COREPRIME3G_VE),y)
obj-y += sensor_power_coreprime3g_ve.o
else ifeq ($(CONFIG_MACH_SHARKLS_Z3LTE),y)
obj-y += sensor_power_sharkls_z3lte.o
else ifeq ($(CONFIG_MACH_TIZENZ3_3G),y)
obj-y += sensor_power_sharkls_z3lte.o
else
obj-y += sensor_power.o
endif
