#
# Makefile for zte touchscreen driver.
#
obj-$(CONFIG_ZTE_TOUCHSCREEN) += tpd_sys.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_V27) += synaptics_2.7/
obj-$(CONFIG_TOUCHSCREEN_FTS_V2_2)	+= focaltech_touch_V2_2/
obj-$(CONFIG_TOUCHSCREEN_TLSC6X)	+= tlsc6x/
obj-$(CONFIG_TOUCHSCREEN_HIMAX_CHIPSET_ONCELL) += hxchipset_oncell/