obj-$(CONFIG_ARCH_SPRD) += sprd-isoc.o

obj-$(CONFIG_X86_SPRD_IWHALE2_LPC) += iwhale2/
obj-$(CONFIG_X86_SPRD_ISHARKL2_LPC) += isharkl2/

obj-$(CONFIG_PM_SLEEP) += pm.o  wakeup_$(BITS).o performance.o
